//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DatagramProcessing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DatagramProcessing;

/**
 * Resultado del procesamiento de un lote
 **/
public class BatchResult implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public String batchId;

    public SpeedStatistics[] statistics;

    public int processedCount;

    public double processingTime;

    public boolean success;

    public String errorMessage;

    public BatchResult()
    {
        this.batchId = "";
        this.errorMessage = "";
    }

    public BatchResult(String batchId, SpeedStatistics[] statistics, int processedCount, double processingTime, boolean success, String errorMessage)
    {
        this.batchId = batchId;
        this.statistics = statistics;
        this.processedCount = processedCount;
        this.processingTime = processingTime;
        this.success = success;
        this.errorMessage = errorMessage;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        BatchResult r = null;
        if(rhs instanceof BatchResult)
        {
            r = (BatchResult)rhs;
        }

        if(r != null)
        {
            if(this.batchId != r.batchId)
            {
                if(this.batchId == null || r.batchId == null || !this.batchId.equals(r.batchId))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(this.statistics, r.statistics))
            {
                return false;
            }
            if(this.processedCount != r.processedCount)
            {
                return false;
            }
            if(this.processingTime != r.processingTime)
            {
                return false;
            }
            if(this.success != r.success)
            {
                return false;
            }
            if(this.errorMessage != r.errorMessage)
            {
                if(this.errorMessage == null || r.errorMessage == null || !this.errorMessage.equals(r.errorMessage))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::DatagramProcessing::BatchResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, batchId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, statistics);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, processedCount);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, processingTime);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, success);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, errorMessage);
        return h_;
    }

    public BatchResult clone()
    {
        BatchResult c = null;
        try
        {
            c = (BatchResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.batchId);
        SpeedStatisticsListHelper.write(ostr, this.statistics);
        ostr.writeInt(this.processedCount);
        ostr.writeDouble(this.processingTime);
        ostr.writeBool(this.success);
        ostr.writeString(this.errorMessage);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.batchId = istr.readString();
        this.statistics = SpeedStatisticsListHelper.read(istr);
        this.processedCount = istr.readInt();
        this.processingTime = istr.readDouble();
        this.success = istr.readBool();
        this.errorMessage = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, BatchResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public BatchResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        BatchResult v = new BatchResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<BatchResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, BatchResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<BatchResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(BatchResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final BatchResult _nullMarshalValue = new BatchResult();

    /** @hidden */
    public static final long serialVersionUID = 1698547087L;
}
