//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DatagramProcessing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DatagramProcessing;

/**
 * Servicio Master para coordinar procesamiento distribuido
 **/
public interface DatagramMasterPrx extends com.zeroc.Ice.ObjectPrx
{
    /**
     * Registra un worker en el sistema
     **/
    default String registerWorker(DatagramWorkerPrx worker)
    {
        return registerWorker(worker, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Registra un worker en el sistema
     * @param context The Context map to send with the invocation.
     **/
    default String registerWorker(DatagramWorkerPrx worker, java.util.Map<String, String> context)
    {
        return _iceI_registerWorkerAsync(worker, context, true).waitForResponse();
    }

    /**
     * Registra un worker en el sistema
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> registerWorkerAsync(DatagramWorkerPrx worker)
    {
        return _iceI_registerWorkerAsync(worker, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Registra un worker en el sistema
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> registerWorkerAsync(DatagramWorkerPrx worker, java.util.Map<String, String> context)
    {
        return _iceI_registerWorkerAsync(worker, context, false);
    }

    /**
     * @hidden
     * @param iceP_worker -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_registerWorkerAsync(DatagramWorkerPrx iceP_worker, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerWorker", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeProxy(iceP_worker);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Desregistra un worker
     **/
    default void unregisterWorker(String workerId)
    {
        unregisterWorker(workerId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Desregistra un worker
     * @param context The Context map to send with the invocation.
     **/
    default void unregisterWorker(String workerId, java.util.Map<String, String> context)
    {
        _iceI_unregisterWorkerAsync(workerId, context, true).waitForResponse();
    }

    /**
     * Desregistra un worker
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> unregisterWorkerAsync(String workerId)
    {
        return _iceI_unregisterWorkerAsync(workerId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Desregistra un worker
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> unregisterWorkerAsync(String workerId, java.util.Map<String, String> context)
    {
        return _iceI_unregisterWorkerAsync(workerId, context, false);
    }

    /**
     * @hidden
     * @param iceP_workerId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unregisterWorkerAsync(String iceP_workerId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unregisterWorker", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_workerId);
                 }, null);
        return f;
    }

    /**
     * Procesa un archivo completo de datagrams de forma distribuida
     * @param filePath Ruta al archivo datagrams.csv
     * @param nodes Lista de nodos del grafo
     * @param batchSize Tamaño de cada lote
     * @return ID del job de procesamiento
     **/
    default String processFile(String filePath, GraphNode[] nodes, int batchSize)
    {
        return processFile(filePath, nodes, batchSize, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Procesa un archivo completo de datagrams de forma distribuida
     * @param filePath Ruta al archivo datagrams.csv
     * @param nodes Lista de nodos del grafo
     * @param batchSize Tamaño de cada lote
     * @param context The Context map to send with the invocation.
     * @return ID del job de procesamiento
     **/
    default String processFile(String filePath, GraphNode[] nodes, int batchSize, java.util.Map<String, String> context)
    {
        return _iceI_processFileAsync(filePath, nodes, batchSize, context, true).waitForResponse();
    }

    /**
     * Procesa un archivo completo de datagrams de forma distribuida
     * @param filePath Ruta al archivo datagrams.csv
     * @param nodes Lista de nodos del grafo
     * @param batchSize Tamaño de cada lote
     * @return ID del job de procesamiento
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> processFileAsync(String filePath, GraphNode[] nodes, int batchSize)
    {
        return _iceI_processFileAsync(filePath, nodes, batchSize, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Procesa un archivo completo de datagrams de forma distribuida
     * @param filePath Ruta al archivo datagrams.csv
     * @param nodes Lista de nodos del grafo
     * @param batchSize Tamaño de cada lote
     * @param context The Context map to send with the invocation.
     * @return ID del job de procesamiento
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> processFileAsync(String filePath, GraphNode[] nodes, int batchSize, java.util.Map<String, String> context)
    {
        return _iceI_processFileAsync(filePath, nodes, batchSize, context, false);
    }

    /**
     * @hidden
     * @param iceP_filePath -
     * @param iceP_nodes -
     * @param iceP_batchSize -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_processFileAsync(String iceP_filePath, GraphNode[] iceP_nodes, int iceP_batchSize, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "processFile", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_filePath);
                     GraphNodeArrayHelper.write(ostr, iceP_nodes);
                     ostr.writeInt(iceP_batchSize);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Inicia un nuevo job de procesamiento (sin leer archivo)
     * El cliente enviará los lotes directamente usando submitBatch
     * @param nodes Lista de nodos del grafo
     * @param totalBatches Número total de lotes que se enviarán
     * @return ID del job de procesamiento
     **/
    default String startJob(GraphNode[] nodes, int totalBatches)
    {
        return startJob(nodes, totalBatches, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Inicia un nuevo job de procesamiento (sin leer archivo)
     * El cliente enviará los lotes directamente usando submitBatch
     * @param nodes Lista de nodos del grafo
     * @param totalBatches Número total de lotes que se enviarán
     * @param context The Context map to send with the invocation.
     * @return ID del job de procesamiento
     **/
    default String startJob(GraphNode[] nodes, int totalBatches, java.util.Map<String, String> context)
    {
        return _iceI_startJobAsync(nodes, totalBatches, context, true).waitForResponse();
    }

    /**
     * Inicia un nuevo job de procesamiento (sin leer archivo)
     * El cliente enviará los lotes directamente usando submitBatch
     * @param nodes Lista de nodos del grafo
     * @param totalBatches Número total de lotes que se enviarán
     * @return ID del job de procesamiento
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> startJobAsync(GraphNode[] nodes, int totalBatches)
    {
        return _iceI_startJobAsync(nodes, totalBatches, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Inicia un nuevo job de procesamiento (sin leer archivo)
     * El cliente enviará los lotes directamente usando submitBatch
     * @param nodes Lista de nodos del grafo
     * @param totalBatches Número total de lotes que se enviarán
     * @param context The Context map to send with the invocation.
     * @return ID del job de procesamiento
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> startJobAsync(GraphNode[] nodes, int totalBatches, java.util.Map<String, String> context)
    {
        return _iceI_startJobAsync(nodes, totalBatches, context, false);
    }

    /**
     * @hidden
     * @param iceP_nodes -
     * @param iceP_totalBatches -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_startJobAsync(GraphNode[] iceP_nodes, int iceP_totalBatches, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startJob", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     GraphNodeArrayHelper.write(ostr, iceP_nodes);
                     ostr.writeInt(iceP_totalBatches);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Envía un lote de datagrams para procesamiento
     * @param jobId ID del job iniciado con startJob
     * @param batch Lote de datagrams a procesar
     * @param batchNumber Número de lote (0-based)
     * @return true si el lote fue aceptado
     **/
    default boolean submitBatch(String jobId, Datagram[] batch, int batchNumber)
    {
        return submitBatch(jobId, batch, batchNumber, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Envía un lote de datagrams para procesamiento
     * @param jobId ID del job iniciado con startJob
     * @param batch Lote de datagrams a procesar
     * @param batchNumber Número de lote (0-based)
     * @param context The Context map to send with the invocation.
     * @return true si el lote fue aceptado
     **/
    default boolean submitBatch(String jobId, Datagram[] batch, int batchNumber, java.util.Map<String, String> context)
    {
        return _iceI_submitBatchAsync(jobId, batch, batchNumber, context, true).waitForResponse();
    }

    /**
     * Envía un lote de datagrams para procesamiento
     * @param jobId ID del job iniciado con startJob
     * @param batch Lote de datagrams a procesar
     * @param batchNumber Número de lote (0-based)
     * @return true si el lote fue aceptado
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Boolean> submitBatchAsync(String jobId, Datagram[] batch, int batchNumber)
    {
        return _iceI_submitBatchAsync(jobId, batch, batchNumber, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Envía un lote de datagrams para procesamiento
     * @param jobId ID del job iniciado con startJob
     * @param batch Lote de datagrams a procesar
     * @param batchNumber Número de lote (0-based)
     * @param context The Context map to send with the invocation.
     * @return true si el lote fue aceptado
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Boolean> submitBatchAsync(String jobId, Datagram[] batch, int batchNumber, java.util.Map<String, String> context)
    {
        return _iceI_submitBatchAsync(jobId, batch, batchNumber, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param iceP_batch -
     * @param iceP_batchNumber -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_submitBatchAsync(String iceP_jobId, Datagram[] iceP_batch, int iceP_batchNumber, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "submitBatch", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                     DatagramBatchHelper.write(ostr, iceP_batch);
                     ostr.writeInt(iceP_batchNumber);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /**
     * Marca un job como completado (todos los lotes han sido enviados)
     * @param jobId ID del job
     **/
    default void completeJob(String jobId)
    {
        completeJob(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Marca un job como completado (todos los lotes han sido enviados)
     * @param jobId ID del job
     * @param context The Context map to send with the invocation.
     **/
    default void completeJob(String jobId, java.util.Map<String, String> context)
    {
        _iceI_completeJobAsync(jobId, context, true).waitForResponse();
    }

    /**
     * Marca un job como completado (todos los lotes han sido enviados)
     * @param jobId ID del job
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> completeJobAsync(String jobId)
    {
        return _iceI_completeJobAsync(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Marca un job como completado (todos los lotes han sido enviados)
     * @param jobId ID del job
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> completeJobAsync(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_completeJobAsync(jobId, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_completeJobAsync(String iceP_jobId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "completeJob", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                 }, null);
        return f;
    }

    /**
     * Obtiene el progreso de un job
     * @param jobId ID del job
     * @return Porcentaje completado (0-100)
     **/
    default int getJobProgress(String jobId)
    {
        return getJobProgress(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene el progreso de un job
     * @param jobId ID del job
     * @param context The Context map to send with the invocation.
     * @return Porcentaje completado (0-100)
     **/
    default int getJobProgress(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getJobProgressAsync(jobId, context, true).waitForResponse();
    }

    /**
     * Obtiene el progreso de un job
     * @param jobId ID del job
     * @return Porcentaje completado (0-100)
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Integer> getJobProgressAsync(String jobId)
    {
        return _iceI_getJobProgressAsync(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene el progreso de un job
     * @param jobId ID del job
     * @param context The Context map to send with the invocation.
     * @return Porcentaje completado (0-100)
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Integer> getJobProgressAsync(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getJobProgressAsync(jobId, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getJobProgressAsync(String iceP_jobId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getJobProgress", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Obtiene los resultados de un job completado
     * @param jobId ID del job
     * @return Lista de estadísticas de velocidad
     **/
    default SpeedStatistics[] getJobResults(String jobId)
    {
        return getJobResults(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene los resultados de un job completado
     * @param jobId ID del job
     * @param context The Context map to send with the invocation.
     * @return Lista de estadísticas de velocidad
     **/
    default SpeedStatistics[] getJobResults(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getJobResultsAsync(jobId, context, true).waitForResponse();
    }

    /**
     * Obtiene los resultados de un job completado
     * @param jobId ID del job
     * @return Lista de estadísticas de velocidad
     **/
    default java.util.concurrent.CompletableFuture<SpeedStatistics[]> getJobResultsAsync(String jobId)
    {
        return _iceI_getJobResultsAsync(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene los resultados de un job completado
     * @param jobId ID del job
     * @param context The Context map to send with the invocation.
     * @return Lista de estadísticas de velocidad
     **/
    default java.util.concurrent.CompletableFuture<SpeedStatistics[]> getJobResultsAsync(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getJobResultsAsync(jobId, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<SpeedStatistics[]> _iceI_getJobResultsAsync(String iceP_jobId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<SpeedStatistics[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getJobResults", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                 }, istr -> {
                     SpeedStatistics[] ret;
                     ret = SpeedStatisticsListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Obtiene el número de workers disponibles
     **/
    default int getWorkerCount()
    {
        return getWorkerCount(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene el número de workers disponibles
     * @param context The Context map to send with the invocation.
     **/
    default int getWorkerCount(java.util.Map<String, String> context)
    {
        return _iceI_getWorkerCountAsync(context, true).waitForResponse();
    }

    /**
     * Obtiene el número de workers disponibles
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Integer> getWorkerCountAsync()
    {
        return _iceI_getWorkerCountAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene el número de workers disponibles
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Integer> getWorkerCountAsync(java.util.Map<String, String> context)
    {
        return _iceI_getWorkerCountAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getWorkerCountAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getWorkerCount", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static DatagramMasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), DatagramMasterPrx.class, _DatagramMasterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static DatagramMasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), DatagramMasterPrx.class, _DatagramMasterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static DatagramMasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), DatagramMasterPrx.class, _DatagramMasterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static DatagramMasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), DatagramMasterPrx.class, _DatagramMasterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static DatagramMasterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, DatagramMasterPrx.class, _DatagramMasterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static DatagramMasterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, DatagramMasterPrx.class, _DatagramMasterPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default DatagramMasterPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (DatagramMasterPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default DatagramMasterPrx ice_adapterId(String newAdapterId)
    {
        return (DatagramMasterPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default DatagramMasterPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (DatagramMasterPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default DatagramMasterPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (DatagramMasterPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default DatagramMasterPrx ice_invocationTimeout(int newTimeout)
    {
        return (DatagramMasterPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default DatagramMasterPrx ice_connectionCached(boolean newCache)
    {
        return (DatagramMasterPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default DatagramMasterPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (DatagramMasterPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default DatagramMasterPrx ice_secure(boolean b)
    {
        return (DatagramMasterPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default DatagramMasterPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (DatagramMasterPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default DatagramMasterPrx ice_preferSecure(boolean b)
    {
        return (DatagramMasterPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default DatagramMasterPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (DatagramMasterPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default DatagramMasterPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (DatagramMasterPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default DatagramMasterPrx ice_collocationOptimized(boolean b)
    {
        return (DatagramMasterPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default DatagramMasterPrx ice_twoway()
    {
        return (DatagramMasterPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default DatagramMasterPrx ice_oneway()
    {
        return (DatagramMasterPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default DatagramMasterPrx ice_batchOneway()
    {
        return (DatagramMasterPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default DatagramMasterPrx ice_datagram()
    {
        return (DatagramMasterPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default DatagramMasterPrx ice_batchDatagram()
    {
        return (DatagramMasterPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default DatagramMasterPrx ice_compress(boolean co)
    {
        return (DatagramMasterPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default DatagramMasterPrx ice_timeout(int t)
    {
        return (DatagramMasterPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default DatagramMasterPrx ice_connectionId(String connectionId)
    {
        return (DatagramMasterPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default DatagramMasterPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (DatagramMasterPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::DatagramProcessing::DatagramMaster";
    }
}
