//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DatagramProcessing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DatagramProcessing;

/**
 * Helper class for marshaling/unmarshaling DatagramBatch.
 **/
public final class DatagramBatchHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Datagram[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Datagram.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Datagram[] read(com.zeroc.Ice.InputStream istr)
    {
        final Datagram[] v;
        final int len0 = istr.readAndCheckSeqSize(31);
        v = new Datagram[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Datagram.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Datagram[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Datagram[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            DatagramBatchHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Datagram[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Datagram[] v;
            v = DatagramBatchHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
