//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DatagramProcessing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DatagramProcessing;

/**
 * Servicio Worker para procesar lotes de datagrams
 **/
public interface DatagramWorkerPrx extends com.zeroc.Ice.ObjectPrx
{
    /**
     * Procesa un lote de datagrams y retorna estadísticas de velocidad
     * @param batch Lote de datagrams a procesar
     * @param nodes Lista de nodos del grafo para cálculo de distancias
     * @return Resultado del procesamiento
     **/
    default BatchResult processBatch(Datagram[] batch, GraphNode[] nodes)
    {
        return processBatch(batch, nodes, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Procesa un lote de datagrams y retorna estadísticas de velocidad
     * @param batch Lote de datagrams a procesar
     * @param nodes Lista de nodos del grafo para cálculo de distancias
     * @param context The Context map to send with the invocation.
     * @return Resultado del procesamiento
     **/
    default BatchResult processBatch(Datagram[] batch, GraphNode[] nodes, java.util.Map<String, String> context)
    {
        return _iceI_processBatchAsync(batch, nodes, context, true).waitForResponse();
    }

    /**
     * Procesa un lote de datagrams y retorna estadísticas de velocidad
     * @param batch Lote de datagrams a procesar
     * @param nodes Lista de nodos del grafo para cálculo de distancias
     * @return Resultado del procesamiento
     **/
    default java.util.concurrent.CompletableFuture<BatchResult> processBatchAsync(Datagram[] batch, GraphNode[] nodes)
    {
        return _iceI_processBatchAsync(batch, nodes, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Procesa un lote de datagrams y retorna estadísticas de velocidad
     * @param batch Lote de datagrams a procesar
     * @param nodes Lista de nodos del grafo para cálculo de distancias
     * @param context The Context map to send with the invocation.
     * @return Resultado del procesamiento
     **/
    default java.util.concurrent.CompletableFuture<BatchResult> processBatchAsync(Datagram[] batch, GraphNode[] nodes, java.util.Map<String, String> context)
    {
        return _iceI_processBatchAsync(batch, nodes, context, false);
    }

    /**
     * @hidden
     * @param iceP_batch -
     * @param iceP_nodes -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<BatchResult> _iceI_processBatchAsync(Datagram[] iceP_batch, GraphNode[] iceP_nodes, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<BatchResult> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "processBatch", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     DatagramBatchHelper.write(ostr, iceP_batch);
                     GraphNodeArrayHelper.write(ostr, iceP_nodes);
                 }, istr -> {
                     BatchResult ret;
                     ret = BatchResult.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Verifica si el worker está disponible
     **/
    default boolean isAvailable()
    {
        return isAvailable(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Verifica si el worker está disponible
     * @param context The Context map to send with the invocation.
     **/
    default boolean isAvailable(java.util.Map<String, String> context)
    {
        return _iceI_isAvailableAsync(context, true).waitForResponse();
    }

    /**
     * Verifica si el worker está disponible
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isAvailableAsync()
    {
        return _iceI_isAvailableAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Verifica si el worker está disponible
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isAvailableAsync(java.util.Map<String, String> context)
    {
        return _iceI_isAvailableAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_isAvailableAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "isAvailable", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /**
     * Obtiene el ID del worker
     **/
    default String getWorkerId()
    {
        return getWorkerId(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene el ID del worker
     * @param context The Context map to send with the invocation.
     **/
    default String getWorkerId(java.util.Map<String, String> context)
    {
        return _iceI_getWorkerIdAsync(context, true).waitForResponse();
    }

    /**
     * Obtiene el ID del worker
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> getWorkerIdAsync()
    {
        return _iceI_getWorkerIdAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene el ID del worker
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> getWorkerIdAsync(java.util.Map<String, String> context)
    {
        return _iceI_getWorkerIdAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getWorkerIdAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getWorkerId", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Obtiene estadísticas del worker (carga, tareas procesadas, etc.)
     **/
    default String getStatistics()
    {
        return getStatistics(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtiene estadísticas del worker (carga, tareas procesadas, etc.)
     * @param context The Context map to send with the invocation.
     **/
    default String getStatistics(java.util.Map<String, String> context)
    {
        return _iceI_getStatisticsAsync(context, true).waitForResponse();
    }

    /**
     * Obtiene estadísticas del worker (carga, tareas procesadas, etc.)
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> getStatisticsAsync()
    {
        return _iceI_getStatisticsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtiene estadísticas del worker (carga, tareas procesadas, etc.)
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed with the result.
     **/
    default java.util.concurrent.CompletableFuture<java.lang.String> getStatisticsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getStatisticsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getStatisticsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getStatistics", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static DatagramWorkerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), DatagramWorkerPrx.class, _DatagramWorkerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static DatagramWorkerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), DatagramWorkerPrx.class, _DatagramWorkerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static DatagramWorkerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), DatagramWorkerPrx.class, _DatagramWorkerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static DatagramWorkerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), DatagramWorkerPrx.class, _DatagramWorkerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static DatagramWorkerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, DatagramWorkerPrx.class, _DatagramWorkerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static DatagramWorkerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, DatagramWorkerPrx.class, _DatagramWorkerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default DatagramWorkerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (DatagramWorkerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default DatagramWorkerPrx ice_adapterId(String newAdapterId)
    {
        return (DatagramWorkerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default DatagramWorkerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (DatagramWorkerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default DatagramWorkerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (DatagramWorkerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default DatagramWorkerPrx ice_invocationTimeout(int newTimeout)
    {
        return (DatagramWorkerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default DatagramWorkerPrx ice_connectionCached(boolean newCache)
    {
        return (DatagramWorkerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default DatagramWorkerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (DatagramWorkerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default DatagramWorkerPrx ice_secure(boolean b)
    {
        return (DatagramWorkerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default DatagramWorkerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (DatagramWorkerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default DatagramWorkerPrx ice_preferSecure(boolean b)
    {
        return (DatagramWorkerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default DatagramWorkerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (DatagramWorkerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default DatagramWorkerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (DatagramWorkerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default DatagramWorkerPrx ice_collocationOptimized(boolean b)
    {
        return (DatagramWorkerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default DatagramWorkerPrx ice_twoway()
    {
        return (DatagramWorkerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default DatagramWorkerPrx ice_oneway()
    {
        return (DatagramWorkerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default DatagramWorkerPrx ice_batchOneway()
    {
        return (DatagramWorkerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default DatagramWorkerPrx ice_datagram()
    {
        return (DatagramWorkerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default DatagramWorkerPrx ice_batchDatagram()
    {
        return (DatagramWorkerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default DatagramWorkerPrx ice_compress(boolean co)
    {
        return (DatagramWorkerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default DatagramWorkerPrx ice_timeout(int t)
    {
        return (DatagramWorkerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default DatagramWorkerPrx ice_connectionId(String connectionId)
    {
        return (DatagramWorkerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default DatagramWorkerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (DatagramWorkerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::DatagramProcessing::DatagramWorker";
    }
}
