//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DatagramProcessing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DatagramProcessing;

/**
 * Servicio Master para coordinar procesamiento distribuido
 **/
public interface DatagramMaster extends com.zeroc.Ice.Object
{
    /**
     * Registra un worker en el sistema
     * @param current The Current object for the invocation.
     **/
    String registerWorker(DatagramWorkerPrx worker, com.zeroc.Ice.Current current);

    /**
     * Desregistra un worker
     * @param current The Current object for the invocation.
     **/
    void unregisterWorker(String workerId, com.zeroc.Ice.Current current);

    /**
     * Procesa un archivo completo de datagrams de forma distribuida
     * @param filePath Ruta al archivo datagrams.csv
     * @param nodes Lista de nodos del grafo
     * @param batchSize Tamaño de cada lote
     * @param current The Current object for the invocation.
     * @return ID del job de procesamiento
     **/
    String processFile(String filePath, GraphNode[] nodes, int batchSize, com.zeroc.Ice.Current current);

    /**
     * Obtiene el progreso de un job
     * @param jobId ID del job
     * @param current The Current object for the invocation.
     * @return Porcentaje completado (0-100)
     **/
    int getJobProgress(String jobId, com.zeroc.Ice.Current current);

    /**
     * Obtiene los resultados de un job completado
     * @param jobId ID del job
     * @param current The Current object for the invocation.
     * @return Lista de estadísticas de velocidad
     **/
    SpeedStatistics[] getJobResults(String jobId, com.zeroc.Ice.Current current);

    /**
     * Obtiene el número de workers disponibles
     * @param current The Current object for the invocation.
     **/
    int getWorkerCount(com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::DatagramProcessing::DatagramMaster",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::DatagramProcessing::DatagramMaster";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_registerWorker(DatagramMaster obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        DatagramWorkerPrx iceP_worker;
        iceP_worker = DatagramWorkerPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        String ret = obj.registerWorker(iceP_worker, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_unregisterWorker(DatagramMaster obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_workerId;
        iceP_workerId = istr.readString();
        inS.endReadParams();
        obj.unregisterWorker(iceP_workerId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_processFile(DatagramMaster obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_filePath;
        GraphNode[] iceP_nodes;
        int iceP_batchSize;
        iceP_filePath = istr.readString();
        iceP_nodes = GraphNodeArrayHelper.read(istr);
        iceP_batchSize = istr.readInt();
        inS.endReadParams();
        String ret = obj.processFile(iceP_filePath, iceP_nodes, iceP_batchSize, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getJobProgress(DatagramMaster obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_jobId;
        iceP_jobId = istr.readString();
        inS.endReadParams();
        int ret = obj.getJobProgress(iceP_jobId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeInt(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getJobResults(DatagramMaster obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_jobId;
        iceP_jobId = istr.readString();
        inS.endReadParams();
        SpeedStatistics[] ret = obj.getJobResults(iceP_jobId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SpeedStatisticsListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getWorkerCount(DatagramMaster obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        int ret = obj.getWorkerCount(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeInt(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "getJobProgress",
        "getJobResults",
        "getWorkerCount",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "processFile",
        "registerWorker",
        "unregisterWorker"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_getJobProgress(this, in, current);
            }
            case 1:
            {
                return _iceD_getJobResults(this, in, current);
            }
            case 2:
            {
                return _iceD_getWorkerCount(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 7:
            {
                return _iceD_processFile(this, in, current);
            }
            case 8:
            {
                return _iceD_registerWorker(this, in, current);
            }
            case 9:
            {
                return _iceD_unregisterWorker(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
