//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DatagramProcessing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DatagramProcessing;

/**
 * Representa un datagram (registro GPS de bus)
 **/
public class Datagram implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public String busId;

    public String routeId;

    public String stopId;

    public double latitude;

    public double longitude;

    public long timestamp;

    public int sequenceNumber;

    public Datagram()
    {
        this.busId = "";
        this.routeId = "";
        this.stopId = "";
    }

    public Datagram(String busId, String routeId, String stopId, double latitude, double longitude, long timestamp, int sequenceNumber)
    {
        this.busId = busId;
        this.routeId = routeId;
        this.stopId = stopId;
        this.latitude = latitude;
        this.longitude = longitude;
        this.timestamp = timestamp;
        this.sequenceNumber = sequenceNumber;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Datagram r = null;
        if(rhs instanceof Datagram)
        {
            r = (Datagram)rhs;
        }

        if(r != null)
        {
            if(this.busId != r.busId)
            {
                if(this.busId == null || r.busId == null || !this.busId.equals(r.busId))
                {
                    return false;
                }
            }
            if(this.routeId != r.routeId)
            {
                if(this.routeId == null || r.routeId == null || !this.routeId.equals(r.routeId))
                {
                    return false;
                }
            }
            if(this.stopId != r.stopId)
            {
                if(this.stopId == null || r.stopId == null || !this.stopId.equals(r.stopId))
                {
                    return false;
                }
            }
            if(this.latitude != r.latitude)
            {
                return false;
            }
            if(this.longitude != r.longitude)
            {
                return false;
            }
            if(this.timestamp != r.timestamp)
            {
                return false;
            }
            if(this.sequenceNumber != r.sequenceNumber)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::DatagramProcessing::Datagram");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, busId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sequenceNumber);
        return h_;
    }

    public Datagram clone()
    {
        Datagram c = null;
        try
        {
            c = (Datagram)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.busId);
        ostr.writeString(this.routeId);
        ostr.writeString(this.stopId);
        ostr.writeDouble(this.latitude);
        ostr.writeDouble(this.longitude);
        ostr.writeLong(this.timestamp);
        ostr.writeInt(this.sequenceNumber);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.busId = istr.readString();
        this.routeId = istr.readString();
        this.stopId = istr.readString();
        this.latitude = istr.readDouble();
        this.longitude = istr.readDouble();
        this.timestamp = istr.readLong();
        this.sequenceNumber = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Datagram v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Datagram ice_read(com.zeroc.Ice.InputStream istr)
    {
        Datagram v = new Datagram();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Datagram> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Datagram v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Datagram> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Datagram.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Datagram _nullMarshalValue = new Datagram();

    /** @hidden */
    public static final long serialVersionUID = -1559135122L;
}
