//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DatagramProcessing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DatagramProcessing;

/**
 * Helper class for marshaling/unmarshaling GraphNodeArray.
 **/
public final class GraphNodeArrayHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, GraphNode[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                GraphNode.ice_write(ostr, v[i0]);
            }
        }
    }

    public static GraphNode[] read(com.zeroc.Ice.InputStream istr)
    {
        final GraphNode[] v;
        final int len0 = istr.readAndCheckSeqSize(19);
        v = new GraphNode[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = GraphNode.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GraphNode[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, GraphNode[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            GraphNodeArrayHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<GraphNode[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            GraphNode[] v;
            v = GraphNodeArrayHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
