//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DatagramProcessing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DatagramProcessing;

/**
 * Nodo del grafo para cálculo de distancias
 **/
public class GraphNode implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String id;

    public String nombre;

    public String tipo;

    public double longitud;

    public double latitud;

    public GraphNode()
    {
        this.id = "";
        this.nombre = "";
        this.tipo = "";
    }

    public GraphNode(String id, String nombre, String tipo, double longitud, double latitud)
    {
        this.id = id;
        this.nombre = nombre;
        this.tipo = tipo;
        this.longitud = longitud;
        this.latitud = latitud;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        GraphNode r = null;
        if(rhs instanceof GraphNode)
        {
            r = (GraphNode)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.nombre != r.nombre)
            {
                if(this.nombre == null || r.nombre == null || !this.nombre.equals(r.nombre))
                {
                    return false;
                }
            }
            if(this.tipo != r.tipo)
            {
                if(this.tipo == null || r.tipo == null || !this.tipo.equals(r.tipo))
                {
                    return false;
                }
            }
            if(this.longitud != r.longitud)
            {
                return false;
            }
            if(this.latitud != r.latitud)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::DatagramProcessing::GraphNode");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nombre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tipo);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longitud);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latitud);
        return h_;
    }

    public GraphNode clone()
    {
        GraphNode c = null;
        try
        {
            c = (GraphNode)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.id);
        ostr.writeString(this.nombre);
        ostr.writeString(this.tipo);
        ostr.writeDouble(this.longitud);
        ostr.writeDouble(this.latitud);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readString();
        this.nombre = istr.readString();
        this.tipo = istr.readString();
        this.longitud = istr.readDouble();
        this.latitud = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, GraphNode v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public GraphNode ice_read(com.zeroc.Ice.InputStream istr)
    {
        GraphNode v = new GraphNode();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GraphNode> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, GraphNode v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<GraphNode> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(GraphNode.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final GraphNode _nullMarshalValue = new GraphNode();

    /** @hidden */
    public static final long serialVersionUID = 1857670311L;
}
