//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DatagramProcessing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DatagramProcessing;

/**
 * Estadísticas de velocidad calculadas
 **/
public class SpeedStatistics implements java.lang.Cloneable,
                                        java.io.Serializable
{
    public String routeId;

    public String origenStopId;

    public String destinoStopId;

    public double distancia;

    public double tiempoPromedio;

    public double velocidadPromedio;

    public int numMuestras;

    public SpeedStatistics()
    {
        this.routeId = "";
        this.origenStopId = "";
        this.destinoStopId = "";
    }

    public SpeedStatistics(String routeId, String origenStopId, String destinoStopId, double distancia, double tiempoPromedio, double velocidadPromedio, int numMuestras)
    {
        this.routeId = routeId;
        this.origenStopId = origenStopId;
        this.destinoStopId = destinoStopId;
        this.distancia = distancia;
        this.tiempoPromedio = tiempoPromedio;
        this.velocidadPromedio = velocidadPromedio;
        this.numMuestras = numMuestras;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        SpeedStatistics r = null;
        if(rhs instanceof SpeedStatistics)
        {
            r = (SpeedStatistics)rhs;
        }

        if(r != null)
        {
            if(this.routeId != r.routeId)
            {
                if(this.routeId == null || r.routeId == null || !this.routeId.equals(r.routeId))
                {
                    return false;
                }
            }
            if(this.origenStopId != r.origenStopId)
            {
                if(this.origenStopId == null || r.origenStopId == null || !this.origenStopId.equals(r.origenStopId))
                {
                    return false;
                }
            }
            if(this.destinoStopId != r.destinoStopId)
            {
                if(this.destinoStopId == null || r.destinoStopId == null || !this.destinoStopId.equals(r.destinoStopId))
                {
                    return false;
                }
            }
            if(this.distancia != r.distancia)
            {
                return false;
            }
            if(this.tiempoPromedio != r.tiempoPromedio)
            {
                return false;
            }
            if(this.velocidadPromedio != r.velocidadPromedio)
            {
                return false;
            }
            if(this.numMuestras != r.numMuestras)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::DatagramProcessing::SpeedStatistics");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, origenStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, destinoStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, distancia);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tiempoPromedio);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, velocidadPromedio);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, numMuestras);
        return h_;
    }

    public SpeedStatistics clone()
    {
        SpeedStatistics c = null;
        try
        {
            c = (SpeedStatistics)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.routeId);
        ostr.writeString(this.origenStopId);
        ostr.writeString(this.destinoStopId);
        ostr.writeDouble(this.distancia);
        ostr.writeDouble(this.tiempoPromedio);
        ostr.writeDouble(this.velocidadPromedio);
        ostr.writeInt(this.numMuestras);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.routeId = istr.readString();
        this.origenStopId = istr.readString();
        this.destinoStopId = istr.readString();
        this.distancia = istr.readDouble();
        this.tiempoPromedio = istr.readDouble();
        this.velocidadPromedio = istr.readDouble();
        this.numMuestras = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, SpeedStatistics v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public SpeedStatistics ice_read(com.zeroc.Ice.InputStream istr)
    {
        SpeedStatistics v = new SpeedStatistics();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SpeedStatistics> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, SpeedStatistics v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<SpeedStatistics> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(SpeedStatistics.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final SpeedStatistics _nullMarshalValue = new SpeedStatistics();

    /** @hidden */
    public static final long serialVersionUID = -2126864131L;
}
