//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `AnalysisService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface AnalysisServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default double calcularVelocidadPromedioGeneral()
    {
        return calcularVelocidadPromedioGeneral(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default double calcularVelocidadPromedioGeneral(java.util.Map<String, String> context)
    {
        return _iceI_calcularVelocidadPromedioGeneralAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> calcularVelocidadPromedioGeneralAsync()
    {
        return _iceI_calcularVelocidadPromedioGeneralAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> calcularVelocidadPromedioGeneralAsync(java.util.Map<String, String> context)
    {
        return _iceI_calcularVelocidadPromedioGeneralAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> _iceI_calcularVelocidadPromedioGeneralAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "calcularVelocidadPromedioGeneral", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     double ret;
                     ret = istr.readDouble();
                     return ret;
                 });
        return f;
    }

    default double calcularVelocidadPromedioRuta(String routeId)
        throws RouteNotFoundException
    {
        return calcularVelocidadPromedioRuta(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default double calcularVelocidadPromedioRuta(String routeId, java.util.Map<String, String> context)
        throws RouteNotFoundException
    {
        try
        {
            return _iceI_calcularVelocidadPromedioRutaAsync(routeId, context, true).waitForResponseOrUserEx();
        }
        catch(RouteNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> calcularVelocidadPromedioRutaAsync(String routeId)
    {
        return _iceI_calcularVelocidadPromedioRutaAsync(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> calcularVelocidadPromedioRutaAsync(String routeId, java.util.Map<String, String> context)
    {
        return _iceI_calcularVelocidadPromedioRutaAsync(routeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> _iceI_calcularVelocidadPromedioRutaAsync(String iceP_routeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "calcularVelocidadPromedioRuta", null, sync, _iceE_calcularVelocidadPromedioRuta);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_routeId);
                 }, istr -> {
                     double ret;
                     ret = istr.readDouble();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_calcularVelocidadPromedioRuta =
    {
        RouteNotFoundException.class
    };

    default VelocityAnalysis[] obtenerAnalisisVelocidadesPorRuta()
    {
        return obtenerAnalisisVelocidadesPorRuta(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default VelocityAnalysis[] obtenerAnalisisVelocidadesPorRuta(java.util.Map<String, String> context)
    {
        return _iceI_obtenerAnalisisVelocidadesPorRutaAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<VelocityAnalysis[]> obtenerAnalisisVelocidadesPorRutaAsync()
    {
        return _iceI_obtenerAnalisisVelocidadesPorRutaAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<VelocityAnalysis[]> obtenerAnalisisVelocidadesPorRutaAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerAnalisisVelocidadesPorRutaAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<VelocityAnalysis[]> _iceI_obtenerAnalisisVelocidadesPorRutaAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<VelocityAnalysis[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerAnalisisVelocidadesPorRuta", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     VelocityAnalysis[] ret;
                     ret = VelocityAnalysisListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default ArcVelocity obtenerArcoMasRapido()
    {
        return obtenerArcoMasRapido(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcVelocity obtenerArcoMasRapido(java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcoMasRapidoAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ArcVelocity> obtenerArcoMasRapidoAsync()
    {
        return _iceI_obtenerArcoMasRapidoAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcVelocity> obtenerArcoMasRapidoAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcoMasRapidoAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcVelocity> _iceI_obtenerArcoMasRapidoAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcVelocity> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerArcoMasRapido", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     ArcVelocity ret;
                     ret = ArcVelocity.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default ArcVelocity obtenerArcoMasLento()
    {
        return obtenerArcoMasLento(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcVelocity obtenerArcoMasLento(java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcoMasLentoAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ArcVelocity> obtenerArcoMasLentoAsync()
    {
        return _iceI_obtenerArcoMasLentoAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcVelocity> obtenerArcoMasLentoAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcoMasLentoAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcVelocity> _iceI_obtenerArcoMasLentoAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcVelocity> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerArcoMasLento", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     ArcVelocity ret;
                     ret = ArcVelocity.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default ArcVelocity[] obtenerVelocidadesArcosRuta(String routeId)
        throws RouteNotFoundException
    {
        return obtenerVelocidadesArcosRuta(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcVelocity[] obtenerVelocidadesArcosRuta(String routeId, java.util.Map<String, String> context)
        throws RouteNotFoundException
    {
        try
        {
            return _iceI_obtenerVelocidadesArcosRutaAsync(routeId, context, true).waitForResponseOrUserEx();
        }
        catch(RouteNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<ArcVelocity[]> obtenerVelocidadesArcosRutaAsync(String routeId)
    {
        return _iceI_obtenerVelocidadesArcosRutaAsync(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcVelocity[]> obtenerVelocidadesArcosRutaAsync(String routeId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerVelocidadesArcosRutaAsync(routeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcVelocity[]> _iceI_obtenerVelocidadesArcosRutaAsync(String iceP_routeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcVelocity[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerVelocidadesArcosRuta", null, sync, _iceE_obtenerVelocidadesArcosRuta);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_routeId);
                 }, istr -> {
                     ArcVelocity[] ret;
                     ret = ArcVelocityListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_obtenerVelocidadesArcosRuta =
    {
        RouteNotFoundException.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AnalysisServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), AnalysisServicePrx.class, _AnalysisServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AnalysisServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), AnalysisServicePrx.class, _AnalysisServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AnalysisServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), AnalysisServicePrx.class, _AnalysisServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AnalysisServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), AnalysisServicePrx.class, _AnalysisServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static AnalysisServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, AnalysisServicePrx.class, _AnalysisServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static AnalysisServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, AnalysisServicePrx.class, _AnalysisServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default AnalysisServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (AnalysisServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default AnalysisServicePrx ice_adapterId(String newAdapterId)
    {
        return (AnalysisServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default AnalysisServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (AnalysisServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default AnalysisServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (AnalysisServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default AnalysisServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (AnalysisServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default AnalysisServicePrx ice_connectionCached(boolean newCache)
    {
        return (AnalysisServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default AnalysisServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (AnalysisServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AnalysisServicePrx ice_secure(boolean b)
    {
        return (AnalysisServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default AnalysisServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (AnalysisServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AnalysisServicePrx ice_preferSecure(boolean b)
    {
        return (AnalysisServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default AnalysisServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (AnalysisServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default AnalysisServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (AnalysisServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default AnalysisServicePrx ice_collocationOptimized(boolean b)
    {
        return (AnalysisServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default AnalysisServicePrx ice_twoway()
    {
        return (AnalysisServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default AnalysisServicePrx ice_oneway()
    {
        return (AnalysisServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default AnalysisServicePrx ice_batchOneway()
    {
        return (AnalysisServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default AnalysisServicePrx ice_datagram()
    {
        return (AnalysisServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default AnalysisServicePrx ice_batchDatagram()
    {
        return (AnalysisServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default AnalysisServicePrx ice_compress(boolean co)
    {
        return (AnalysisServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default AnalysisServicePrx ice_timeout(int t)
    {
        return (AnalysisServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default AnalysisServicePrx ice_connectionId(String connectionId)
    {
        return (AnalysisServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default AnalysisServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (AnalysisServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SITMMIO::AnalysisService";
    }
}
