//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `AnalysisService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface AnalysisService extends com.zeroc.Ice.Object
{
    double calcularVelocidadPromedioGeneral(com.zeroc.Ice.Current current);

    double calcularVelocidadPromedioRuta(String routeId, com.zeroc.Ice.Current current)
        throws RouteNotFoundException;

    VelocityAnalysis[] obtenerAnalisisVelocidadesPorRuta(com.zeroc.Ice.Current current);

    ArcVelocity obtenerArcoMasRapido(com.zeroc.Ice.Current current);

    ArcVelocity obtenerArcoMasLento(com.zeroc.Ice.Current current);

    ArcVelocity[] obtenerVelocidadesArcosRuta(String routeId, com.zeroc.Ice.Current current)
        throws RouteNotFoundException;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::SITMMIO::AnalysisService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::SITMMIO::AnalysisService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_calcularVelocidadPromedioGeneral(AnalysisService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        double ret = obj.calcularVelocidadPromedioGeneral(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeDouble(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_calcularVelocidadPromedioRuta(AnalysisService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_routeId;
        iceP_routeId = istr.readString();
        inS.endReadParams();
        double ret = obj.calcularVelocidadPromedioRuta(iceP_routeId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeDouble(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerAnalisisVelocidadesPorRuta(AnalysisService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        VelocityAnalysis[] ret = obj.obtenerAnalisisVelocidadesPorRuta(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        VelocityAnalysisListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerArcoMasRapido(AnalysisService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        ArcVelocity ret = obj.obtenerArcoMasRapido(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcVelocity.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerArcoMasLento(AnalysisService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        ArcVelocity ret = obj.obtenerArcoMasLento(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcVelocity.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerVelocidadesArcosRuta(AnalysisService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_routeId;
        iceP_routeId = istr.readString();
        inS.endReadParams();
        ArcVelocity[] ret = obj.obtenerVelocidadesArcosRuta(iceP_routeId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcVelocityListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "calcularVelocidadPromedioGeneral",
        "calcularVelocidadPromedioRuta",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "obtenerAnalisisVelocidadesPorRuta",
        "obtenerArcoMasLento",
        "obtenerArcoMasRapido",
        "obtenerVelocidadesArcosRuta"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_calcularVelocidadPromedioGeneral(this, in, current);
            }
            case 1:
            {
                return _iceD_calcularVelocidadPromedioRuta(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 6:
            {
                return _iceD_obtenerAnalisisVelocidadesPorRuta(this, in, current);
            }
            case 7:
            {
                return _iceD_obtenerArcoMasLento(this, in, current);
            }
            case 8:
            {
                return _iceD_obtenerArcoMasRapido(this, in, current);
            }
            case 9:
            {
                return _iceD_obtenerVelocidadesArcosRuta(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
