//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `RouteService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

/**
 * Helper class for marshaling/unmarshaling ArcDetailList.
 **/
public final class ArcDetailListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, ArcDetail[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ArcDetail.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ArcDetail[] read(com.zeroc.Ice.InputStream istr)
    {
        final ArcDetail[] v;
        final int len0 = istr.readAndCheckSeqSize(32);
        v = new ArcDetail[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = ArcDetail.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcDetail[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ArcDetail[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ArcDetailListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<ArcDetail[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            ArcDetail[] v;
            v = ArcDetailListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
