//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `RouteService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class ArcDetail implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String origenId;

    public String origenNombre;

    public String destinoId;

    public String destinoNombre;

    public int secuencia;

    public double distancia;

    public double tiempo;

    public double velocidad;

    public ArcDetail()
    {
        this.origenId = "";
        this.origenNombre = "";
        this.destinoId = "";
        this.destinoNombre = "";
    }

    public ArcDetail(String origenId, String origenNombre, String destinoId, String destinoNombre, int secuencia, double distancia, double tiempo, double velocidad)
    {
        this.origenId = origenId;
        this.origenNombre = origenNombre;
        this.destinoId = destinoId;
        this.destinoNombre = destinoNombre;
        this.secuencia = secuencia;
        this.distancia = distancia;
        this.tiempo = tiempo;
        this.velocidad = velocidad;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ArcDetail r = null;
        if(rhs instanceof ArcDetail)
        {
            r = (ArcDetail)rhs;
        }

        if(r != null)
        {
            if(this.origenId != r.origenId)
            {
                if(this.origenId == null || r.origenId == null || !this.origenId.equals(r.origenId))
                {
                    return false;
                }
            }
            if(this.origenNombre != r.origenNombre)
            {
                if(this.origenNombre == null || r.origenNombre == null || !this.origenNombre.equals(r.origenNombre))
                {
                    return false;
                }
            }
            if(this.destinoId != r.destinoId)
            {
                if(this.destinoId == null || r.destinoId == null || !this.destinoId.equals(r.destinoId))
                {
                    return false;
                }
            }
            if(this.destinoNombre != r.destinoNombre)
            {
                if(this.destinoNombre == null || r.destinoNombre == null || !this.destinoNombre.equals(r.destinoNombre))
                {
                    return false;
                }
            }
            if(this.secuencia != r.secuencia)
            {
                return false;
            }
            if(this.distancia != r.distancia)
            {
                return false;
            }
            if(this.tiempo != r.tiempo)
            {
                return false;
            }
            if(this.velocidad != r.velocidad)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::ArcDetail");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, origenId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, origenNombre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, destinoId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, destinoNombre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, secuencia);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, distancia);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tiempo);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, velocidad);
        return h_;
    }

    public ArcDetail clone()
    {
        ArcDetail c = null;
        try
        {
            c = (ArcDetail)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.origenId);
        ostr.writeString(this.origenNombre);
        ostr.writeString(this.destinoId);
        ostr.writeString(this.destinoNombre);
        ostr.writeInt(this.secuencia);
        ostr.writeDouble(this.distancia);
        ostr.writeDouble(this.tiempo);
        ostr.writeDouble(this.velocidad);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.origenId = istr.readString();
        this.origenNombre = istr.readString();
        this.destinoId = istr.readString();
        this.destinoNombre = istr.readString();
        this.secuencia = istr.readInt();
        this.distancia = istr.readDouble();
        this.tiempo = istr.readDouble();
        this.velocidad = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ArcDetail v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ArcDetail ice_read(com.zeroc.Ice.InputStream istr)
    {
        ArcDetail v = new ArcDetail();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcDetail> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ArcDetail v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ArcDetail> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ArcDetail.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ArcDetail _nullMarshalValue = new ArcDetail();

    /** @hidden */
    public static final long serialVersionUID = -274199299L;
}
