//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `AnalysisService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class ArcVelocity implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public String origenId;

    public String destinoId;

    public String ruta;

    public double distancia;

    public double tiempo;

    public double velocidad;

    public ArcVelocity()
    {
        this.origenId = "";
        this.destinoId = "";
        this.ruta = "";
    }

    public ArcVelocity(String origenId, String destinoId, String ruta, double distancia, double tiempo, double velocidad)
    {
        this.origenId = origenId;
        this.destinoId = destinoId;
        this.ruta = ruta;
        this.distancia = distancia;
        this.tiempo = tiempo;
        this.velocidad = velocidad;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ArcVelocity r = null;
        if(rhs instanceof ArcVelocity)
        {
            r = (ArcVelocity)rhs;
        }

        if(r != null)
        {
            if(this.origenId != r.origenId)
            {
                if(this.origenId == null || r.origenId == null || !this.origenId.equals(r.origenId))
                {
                    return false;
                }
            }
            if(this.destinoId != r.destinoId)
            {
                if(this.destinoId == null || r.destinoId == null || !this.destinoId.equals(r.destinoId))
                {
                    return false;
                }
            }
            if(this.ruta != r.ruta)
            {
                if(this.ruta == null || r.ruta == null || !this.ruta.equals(r.ruta))
                {
                    return false;
                }
            }
            if(this.distancia != r.distancia)
            {
                return false;
            }
            if(this.tiempo != r.tiempo)
            {
                return false;
            }
            if(this.velocidad != r.velocidad)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::ArcVelocity");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, origenId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, destinoId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ruta);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, distancia);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tiempo);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, velocidad);
        return h_;
    }

    public ArcVelocity clone()
    {
        ArcVelocity c = null;
        try
        {
            c = (ArcVelocity)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.origenId);
        ostr.writeString(this.destinoId);
        ostr.writeString(this.ruta);
        ostr.writeDouble(this.distancia);
        ostr.writeDouble(this.tiempo);
        ostr.writeDouble(this.velocidad);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.origenId = istr.readString();
        this.destinoId = istr.readString();
        this.ruta = istr.readString();
        this.distancia = istr.readDouble();
        this.tiempo = istr.readDouble();
        this.velocidad = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ArcVelocity v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ArcVelocity ice_read(com.zeroc.Ice.InputStream istr)
    {
        ArcVelocity v = new ArcVelocity();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcVelocity> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ArcVelocity v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ArcVelocity> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ArcVelocity.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ArcVelocity _nullMarshalValue = new ArcVelocity();

    /** @hidden */
    public static final long serialVersionUID = -1249179297L;
}
