//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface CachedGraphServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default Node[] obtenerNodosCached()
    {
        return obtenerNodosCached(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Node[] obtenerNodosCached(java.util.Map<String, String> context)
    {
        return _iceI_obtenerNodosCachedAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Node[]> obtenerNodosCachedAsync()
    {
        return _iceI_obtenerNodosCachedAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Node[]> obtenerNodosCachedAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerNodosCachedAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Node[]> _iceI_obtenerNodosCachedAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Node[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerNodosCached", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Node[] ret;
                     ret = NodeListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default Edge[] obtenerArcosCached()
    {
        return obtenerArcosCached(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Edge[] obtenerArcosCached(java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcosCachedAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerArcosCachedAsync()
    {
        return _iceI_obtenerArcosCachedAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerArcosCachedAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcosCachedAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Edge[]> _iceI_obtenerArcosCachedAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Edge[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerArcosCached", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Edge[] ret;
                     ret = EdgeListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void invalidateCache()
    {
        invalidateCache(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void invalidateCache(java.util.Map<String, String> context)
    {
        _iceI_invalidateCacheAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> invalidateCacheAsync()
    {
        return _iceI_invalidateCacheAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> invalidateCacheAsync(java.util.Map<String, String> context)
    {
        return _iceI_invalidateCacheAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_invalidateCacheAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "invalidateCache", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void setCacheTimeout(int seconds)
    {
        setCacheTimeout(seconds, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setCacheTimeout(int seconds, java.util.Map<String, String> context)
    {
        _iceI_setCacheTimeoutAsync(seconds, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> setCacheTimeoutAsync(int seconds)
    {
        return _iceI_setCacheTimeoutAsync(seconds, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setCacheTimeoutAsync(int seconds, java.util.Map<String, String> context)
    {
        return _iceI_setCacheTimeoutAsync(seconds, context, false);
    }

    /**
     * @hidden
     * @param iceP_seconds -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setCacheTimeoutAsync(int iceP_seconds, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setCacheTimeout", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_seconds);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CachedGraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), CachedGraphServicePrx.class, _CachedGraphServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CachedGraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), CachedGraphServicePrx.class, _CachedGraphServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CachedGraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), CachedGraphServicePrx.class, _CachedGraphServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CachedGraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), CachedGraphServicePrx.class, _CachedGraphServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static CachedGraphServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, CachedGraphServicePrx.class, _CachedGraphServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static CachedGraphServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, CachedGraphServicePrx.class, _CachedGraphServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default CachedGraphServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (CachedGraphServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default CachedGraphServicePrx ice_adapterId(String newAdapterId)
    {
        return (CachedGraphServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default CachedGraphServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (CachedGraphServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default CachedGraphServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (CachedGraphServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default CachedGraphServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (CachedGraphServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default CachedGraphServicePrx ice_connectionCached(boolean newCache)
    {
        return (CachedGraphServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default CachedGraphServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (CachedGraphServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CachedGraphServicePrx ice_secure(boolean b)
    {
        return (CachedGraphServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default CachedGraphServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (CachedGraphServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CachedGraphServicePrx ice_preferSecure(boolean b)
    {
        return (CachedGraphServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default CachedGraphServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (CachedGraphServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default CachedGraphServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (CachedGraphServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default CachedGraphServicePrx ice_collocationOptimized(boolean b)
    {
        return (CachedGraphServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default CachedGraphServicePrx ice_twoway()
    {
        return (CachedGraphServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default CachedGraphServicePrx ice_oneway()
    {
        return (CachedGraphServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default CachedGraphServicePrx ice_batchOneway()
    {
        return (CachedGraphServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default CachedGraphServicePrx ice_datagram()
    {
        return (CachedGraphServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default CachedGraphServicePrx ice_batchDatagram()
    {
        return (CachedGraphServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default CachedGraphServicePrx ice_compress(boolean co)
    {
        return (CachedGraphServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default CachedGraphServicePrx ice_timeout(int t)
    {
        return (CachedGraphServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default CachedGraphServicePrx ice_connectionId(String connectionId)
    {
        return (CachedGraphServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default CachedGraphServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (CachedGraphServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SITMMIO::CachedGraphService";
    }
}
