//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class Edge implements java.lang.Cloneable,
                             java.io.Serializable
{
    public String origenId;

    public String destinoId;

    public String ruta;

    public double distancia;

    public double tiempoPromedio;

    public double velocidadPromedio;

    public Edge()
    {
        this.origenId = "";
        this.destinoId = "";
        this.ruta = "";
    }

    public Edge(String origenId, String destinoId, String ruta, double distancia, double tiempoPromedio, double velocidadPromedio)
    {
        this.origenId = origenId;
        this.destinoId = destinoId;
        this.ruta = ruta;
        this.distancia = distancia;
        this.tiempoPromedio = tiempoPromedio;
        this.velocidadPromedio = velocidadPromedio;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Edge r = null;
        if(rhs instanceof Edge)
        {
            r = (Edge)rhs;
        }

        if(r != null)
        {
            if(this.origenId != r.origenId)
            {
                if(this.origenId == null || r.origenId == null || !this.origenId.equals(r.origenId))
                {
                    return false;
                }
            }
            if(this.destinoId != r.destinoId)
            {
                if(this.destinoId == null || r.destinoId == null || !this.destinoId.equals(r.destinoId))
                {
                    return false;
                }
            }
            if(this.ruta != r.ruta)
            {
                if(this.ruta == null || r.ruta == null || !this.ruta.equals(r.ruta))
                {
                    return false;
                }
            }
            if(this.distancia != r.distancia)
            {
                return false;
            }
            if(this.tiempoPromedio != r.tiempoPromedio)
            {
                return false;
            }
            if(this.velocidadPromedio != r.velocidadPromedio)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::Edge");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, origenId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, destinoId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ruta);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, distancia);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tiempoPromedio);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, velocidadPromedio);
        return h_;
    }

    public Edge clone()
    {
        Edge c = null;
        try
        {
            c = (Edge)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.origenId);
        ostr.writeString(this.destinoId);
        ostr.writeString(this.ruta);
        ostr.writeDouble(this.distancia);
        ostr.writeDouble(this.tiempoPromedio);
        ostr.writeDouble(this.velocidadPromedio);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.origenId = istr.readString();
        this.destinoId = istr.readString();
        this.ruta = istr.readString();
        this.distancia = istr.readDouble();
        this.tiempoPromedio = istr.readDouble();
        this.velocidadPromedio = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Edge v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Edge ice_read(com.zeroc.Ice.InputStream istr)
    {
        Edge v = new Edge();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Edge> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Edge v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Edge> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Edge.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Edge _nullMarshalValue = new Edge();

    /** @hidden */
    public static final long serialVersionUID = 2036169051L;
}
