//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `GraphService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface GraphServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default Node[] obtenerTodosLosNodos()
    {
        return obtenerTodosLosNodos(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Node[] obtenerTodosLosNodos(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTodosLosNodosAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Node[]> obtenerTodosLosNodosAsync()
    {
        return _iceI_obtenerTodosLosNodosAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Node[]> obtenerTodosLosNodosAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTodosLosNodosAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Node[]> _iceI_obtenerTodosLosNodosAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Node[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerTodosLosNodos", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Node[] ret;
                     ret = NodeListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default Node obtenerNodo(String nodeId)
        throws NodeNotFoundException
    {
        return obtenerNodo(nodeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Node obtenerNodo(String nodeId, java.util.Map<String, String> context)
        throws NodeNotFoundException
    {
        try
        {
            return _iceI_obtenerNodoAsync(nodeId, context, true).waitForResponseOrUserEx();
        }
        catch(NodeNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Node> obtenerNodoAsync(String nodeId)
    {
        return _iceI_obtenerNodoAsync(nodeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Node> obtenerNodoAsync(String nodeId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerNodoAsync(nodeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_nodeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Node> _iceI_obtenerNodoAsync(String iceP_nodeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Node> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerNodo", null, sync, _iceE_obtenerNodo);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_nodeId);
                 }, istr -> {
                     Node ret;
                     ret = Node.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_obtenerNodo =
    {
        NodeNotFoundException.class
    };

    default Edge[] obtenerTodosLosArcos()
    {
        return obtenerTodosLosArcos(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Edge[] obtenerTodosLosArcos(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTodosLosArcosAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerTodosLosArcosAsync()
    {
        return _iceI_obtenerTodosLosArcosAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerTodosLosArcosAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTodosLosArcosAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Edge[]> _iceI_obtenerTodosLosArcosAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Edge[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerTodosLosArcos", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Edge[] ret;
                     ret = EdgeListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default Edge[] obtenerArcosPorRuta(String routeId)
        throws RouteNotFoundException
    {
        return obtenerArcosPorRuta(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Edge[] obtenerArcosPorRuta(String routeId, java.util.Map<String, String> context)
        throws RouteNotFoundException
    {
        try
        {
            return _iceI_obtenerArcosPorRutaAsync(routeId, context, true).waitForResponseOrUserEx();
        }
        catch(RouteNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerArcosPorRutaAsync(String routeId)
    {
        return _iceI_obtenerArcosPorRutaAsync(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerArcosPorRutaAsync(String routeId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcosPorRutaAsync(routeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Edge[]> _iceI_obtenerArcosPorRutaAsync(String iceP_routeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Edge[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerArcosPorRuta", null, sync, _iceE_obtenerArcosPorRuta);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_routeId);
                 }, istr -> {
                     Edge[] ret;
                     ret = EdgeListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_obtenerArcosPorRuta =
    {
        RouteNotFoundException.class
    };

    default int obtenerNumeroNodos()
    {
        return obtenerNumeroNodos(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int obtenerNumeroNodos(java.util.Map<String, String> context)
    {
        return _iceI_obtenerNumeroNodosAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerNumeroNodosAsync()
    {
        return _iceI_obtenerNumeroNodosAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerNumeroNodosAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerNumeroNodosAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_obtenerNumeroNodosAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerNumeroNodos", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int obtenerNumeroArcos()
    {
        return obtenerNumeroArcos(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int obtenerNumeroArcos(java.util.Map<String, String> context)
    {
        return _iceI_obtenerNumeroArcosAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerNumeroArcosAsync()
    {
        return _iceI_obtenerNumeroArcosAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerNumeroArcosAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerNumeroArcosAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_obtenerNumeroArcosAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerNumeroArcos", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static GraphServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static GraphServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, GraphServicePrx.class, _GraphServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default GraphServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (GraphServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default GraphServicePrx ice_adapterId(String newAdapterId)
    {
        return (GraphServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default GraphServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (GraphServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default GraphServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (GraphServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default GraphServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (GraphServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default GraphServicePrx ice_connectionCached(boolean newCache)
    {
        return (GraphServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default GraphServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (GraphServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default GraphServicePrx ice_secure(boolean b)
    {
        return (GraphServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default GraphServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (GraphServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default GraphServicePrx ice_preferSecure(boolean b)
    {
        return (GraphServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default GraphServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (GraphServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default GraphServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (GraphServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default GraphServicePrx ice_collocationOptimized(boolean b)
    {
        return (GraphServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default GraphServicePrx ice_twoway()
    {
        return (GraphServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default GraphServicePrx ice_oneway()
    {
        return (GraphServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default GraphServicePrx ice_batchOneway()
    {
        return (GraphServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default GraphServicePrx ice_datagram()
    {
        return (GraphServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default GraphServicePrx ice_batchDatagram()
    {
        return (GraphServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default GraphServicePrx ice_compress(boolean co)
    {
        return (GraphServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default GraphServicePrx ice_timeout(int t)
    {
        return (GraphServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default GraphServicePrx ice_connectionId(String connectionId)
    {
        return (GraphServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default GraphServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (GraphServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SITMMIO::GraphService";
    }
}
