//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface GraphProxyPrx extends com.zeroc.Ice.ObjectPrx
{
    default Node[] obtenerNodos()
    {
        return obtenerNodos(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Node[] obtenerNodos(java.util.Map<String, String> context)
    {
        return _iceI_obtenerNodosAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Node[]> obtenerNodosAsync()
    {
        return _iceI_obtenerNodosAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Node[]> obtenerNodosAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerNodosAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Node[]> _iceI_obtenerNodosAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Node[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerNodos", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Node[] ret;
                     ret = NodeListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default Edge[] obtenerArcos()
    {
        return obtenerArcos(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Edge[] obtenerArcos(java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcosAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerArcosAsync()
    {
        return _iceI_obtenerArcosAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerArcosAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcosAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Edge[]> _iceI_obtenerArcosAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Edge[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerArcos", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Edge[] ret;
                     ret = EdgeListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default Edge[] obtenerArcosPorRuta(String routeId)
    {
        return obtenerArcosPorRuta(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Edge[] obtenerArcosPorRuta(String routeId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcosPorRutaAsync(routeId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerArcosPorRutaAsync(String routeId)
    {
        return _iceI_obtenerArcosPorRutaAsync(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Edge[]> obtenerArcosPorRutaAsync(String routeId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcosPorRutaAsync(routeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Edge[]> _iceI_obtenerArcosPorRutaAsync(String iceP_routeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Edge[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerArcosPorRuta", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_routeId);
                 }, istr -> {
                     Edge[] ret;
                     ret = EdgeListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default boolean isDataLoaded()
    {
        return isDataLoaded(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean isDataLoaded(java.util.Map<String, String> context)
    {
        return _iceI_isDataLoadedAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isDataLoadedAsync()
    {
        return _iceI_isDataLoadedAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isDataLoadedAsync(java.util.Map<String, String> context)
    {
        return _iceI_isDataLoadedAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_isDataLoadedAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "isDataLoaded", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default void preloadData()
    {
        preloadData(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void preloadData(java.util.Map<String, String> context)
    {
        _iceI_preloadDataAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> preloadDataAsync()
    {
        return _iceI_preloadDataAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> preloadDataAsync(java.util.Map<String, String> context)
    {
        return _iceI_preloadDataAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_preloadDataAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "preloadData", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphProxyPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), GraphProxyPrx.class, _GraphProxyPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphProxyPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), GraphProxyPrx.class, _GraphProxyPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphProxyPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), GraphProxyPrx.class, _GraphProxyPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static GraphProxyPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), GraphProxyPrx.class, _GraphProxyPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static GraphProxyPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, GraphProxyPrx.class, _GraphProxyPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static GraphProxyPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, GraphProxyPrx.class, _GraphProxyPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default GraphProxyPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (GraphProxyPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default GraphProxyPrx ice_adapterId(String newAdapterId)
    {
        return (GraphProxyPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default GraphProxyPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (GraphProxyPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default GraphProxyPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (GraphProxyPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default GraphProxyPrx ice_invocationTimeout(int newTimeout)
    {
        return (GraphProxyPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default GraphProxyPrx ice_connectionCached(boolean newCache)
    {
        return (GraphProxyPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default GraphProxyPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (GraphProxyPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default GraphProxyPrx ice_secure(boolean b)
    {
        return (GraphProxyPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default GraphProxyPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (GraphProxyPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default GraphProxyPrx ice_preferSecure(boolean b)
    {
        return (GraphProxyPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default GraphProxyPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (GraphProxyPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default GraphProxyPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (GraphProxyPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default GraphProxyPrx ice_collocationOptimized(boolean b)
    {
        return (GraphProxyPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default GraphProxyPrx ice_twoway()
    {
        return (GraphProxyPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default GraphProxyPrx ice_oneway()
    {
        return (GraphProxyPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default GraphProxyPrx ice_batchOneway()
    {
        return (GraphProxyPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default GraphProxyPrx ice_datagram()
    {
        return (GraphProxyPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default GraphProxyPrx ice_batchDatagram()
    {
        return (GraphProxyPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default GraphProxyPrx ice_compress(boolean co)
    {
        return (GraphProxyPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default GraphProxyPrx ice_timeout(int t)
    {
        return (GraphProxyPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default GraphProxyPrx ice_connectionId(String connectionId)
    {
        return (GraphProxyPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default GraphProxyPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (GraphProxyPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SITMMIO::GraphProxy";
    }
}
