//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class Message implements java.lang.Cloneable,
                                java.io.Serializable
{
    public String messageId;

    public String senderId;

    public String receiverId;

    public String messageType;

    public String payload;

    public long timestamp;

    public int retryCount;

    public Message()
    {
        this.messageId = "";
        this.senderId = "";
        this.receiverId = "";
        this.messageType = "";
        this.payload = "";
    }

    public Message(String messageId, String senderId, String receiverId, String messageType, String payload, long timestamp, int retryCount)
    {
        this.messageId = messageId;
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.messageType = messageType;
        this.payload = payload;
        this.timestamp = timestamp;
        this.retryCount = retryCount;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Message r = null;
        if(rhs instanceof Message)
        {
            r = (Message)rhs;
        }

        if(r != null)
        {
            if(this.messageId != r.messageId)
            {
                if(this.messageId == null || r.messageId == null || !this.messageId.equals(r.messageId))
                {
                    return false;
                }
            }
            if(this.senderId != r.senderId)
            {
                if(this.senderId == null || r.senderId == null || !this.senderId.equals(r.senderId))
                {
                    return false;
                }
            }
            if(this.receiverId != r.receiverId)
            {
                if(this.receiverId == null || r.receiverId == null || !this.receiverId.equals(r.receiverId))
                {
                    return false;
                }
            }
            if(this.messageType != r.messageType)
            {
                if(this.messageType == null || r.messageType == null || !this.messageType.equals(r.messageType))
                {
                    return false;
                }
            }
            if(this.payload != r.payload)
            {
                if(this.payload == null || r.payload == null || !this.payload.equals(r.payload))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                return false;
            }
            if(this.retryCount != r.retryCount)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::Message");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, messageId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, senderId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, receiverId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, messageType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, payload);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, retryCount);
        return h_;
    }

    public Message clone()
    {
        Message c = null;
        try
        {
            c = (Message)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.messageId);
        ostr.writeString(this.senderId);
        ostr.writeString(this.receiverId);
        ostr.writeString(this.messageType);
        ostr.writeString(this.payload);
        ostr.writeLong(this.timestamp);
        ostr.writeInt(this.retryCount);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.messageId = istr.readString();
        this.senderId = istr.readString();
        this.receiverId = istr.readString();
        this.messageType = istr.readString();
        this.payload = istr.readString();
        this.timestamp = istr.readLong();
        this.retryCount = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Message v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Message ice_read(com.zeroc.Ice.InputStream istr)
    {
        Message v = new Message();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Message> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Message v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Message> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Message.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Message _nullMarshalValue = new Message();

    /** @hidden */
    public static final long serialVersionUID = 857756227L;
}
