//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `GraphService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class NodeNotFoundException extends com.zeroc.Ice.UserException
{
    public NodeNotFoundException()
    {
        this.nodeId = "";
    }

    public NodeNotFoundException(Throwable cause)
    {
        super(cause);
        this.nodeId = "";
    }

    public NodeNotFoundException(String nodeId)
    {
        this.nodeId = nodeId;
    }

    public NodeNotFoundException(String nodeId, Throwable cause)
    {
        super(cause);
        this.nodeId = nodeId;
    }

    public String ice_id()
    {
        return "::SITMMIO::NodeNotFoundException";
    }

    public String nodeId;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SITMMIO::NodeNotFoundException", -1, true);
        ostr_.writeString(nodeId);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        nodeId = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 1938311997L;
}
