//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface ReliableMessagingPrx extends com.zeroc.Ice.ObjectPrx
{
    default void sendMessage(Message msg)
    {
        sendMessage(msg, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendMessage(Message msg, java.util.Map<String, String> context)
    {
        _iceI_sendMessageAsync(msg, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageAsync(Message msg)
    {
        return _iceI_sendMessageAsync(msg, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageAsync(Message msg, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageAsync(msg, context, false);
    }

    /**
     * @hidden
     * @param iceP_msg -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendMessageAsync(Message iceP_msg, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Message.ice_write(ostr, iceP_msg);
                 }, null);
        return f;
    }

    default Message receiveMessage(String receiverId)
    {
        return receiveMessage(receiverId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Message receiveMessage(String receiverId, java.util.Map<String, String> context)
    {
        return _iceI_receiveMessageAsync(receiverId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Message> receiveMessageAsync(String receiverId)
    {
        return _iceI_receiveMessageAsync(receiverId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Message> receiveMessageAsync(String receiverId, java.util.Map<String, String> context)
    {
        return _iceI_receiveMessageAsync(receiverId, context, false);
    }

    /**
     * @hidden
     * @param iceP_receiverId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Message> _iceI_receiveMessageAsync(String iceP_receiverId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Message> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "receiveMessage", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_receiverId);
                 }, istr -> {
                     Message ret;
                     ret = Message.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void acknowledgeMessage(String messageId)
    {
        acknowledgeMessage(messageId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void acknowledgeMessage(String messageId, java.util.Map<String, String> context)
    {
        _iceI_acknowledgeMessageAsync(messageId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> acknowledgeMessageAsync(String messageId)
    {
        return _iceI_acknowledgeMessageAsync(messageId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> acknowledgeMessageAsync(String messageId, java.util.Map<String, String> context)
    {
        return _iceI_acknowledgeMessageAsync(messageId, context, false);
    }

    /**
     * @hidden
     * @param iceP_messageId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_acknowledgeMessageAsync(String iceP_messageId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "acknowledgeMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_messageId);
                 }, null);
        return f;
    }

    default Message[] getPendingMessages(String receiverId)
    {
        return getPendingMessages(receiverId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Message[] getPendingMessages(String receiverId, java.util.Map<String, String> context)
    {
        return _iceI_getPendingMessagesAsync(receiverId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Message[]> getPendingMessagesAsync(String receiverId)
    {
        return _iceI_getPendingMessagesAsync(receiverId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Message[]> getPendingMessagesAsync(String receiverId, java.util.Map<String, String> context)
    {
        return _iceI_getPendingMessagesAsync(receiverId, context, false);
    }

    /**
     * @hidden
     * @param iceP_receiverId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Message[]> _iceI_getPendingMessagesAsync(String iceP_receiverId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Message[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPendingMessages", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_receiverId);
                 }, istr -> {
                     Message[] ret;
                     ret = MessageListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReliableMessagingPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ReliableMessagingPrx.class, _ReliableMessagingPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReliableMessagingPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ReliableMessagingPrx.class, _ReliableMessagingPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReliableMessagingPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ReliableMessagingPrx.class, _ReliableMessagingPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReliableMessagingPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ReliableMessagingPrx.class, _ReliableMessagingPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ReliableMessagingPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ReliableMessagingPrx.class, _ReliableMessagingPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ReliableMessagingPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ReliableMessagingPrx.class, _ReliableMessagingPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ReliableMessagingPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ReliableMessagingPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ReliableMessagingPrx ice_adapterId(String newAdapterId)
    {
        return (ReliableMessagingPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ReliableMessagingPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ReliableMessagingPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ReliableMessagingPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ReliableMessagingPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ReliableMessagingPrx ice_invocationTimeout(int newTimeout)
    {
        return (ReliableMessagingPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ReliableMessagingPrx ice_connectionCached(boolean newCache)
    {
        return (ReliableMessagingPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ReliableMessagingPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ReliableMessagingPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ReliableMessagingPrx ice_secure(boolean b)
    {
        return (ReliableMessagingPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ReliableMessagingPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ReliableMessagingPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ReliableMessagingPrx ice_preferSecure(boolean b)
    {
        return (ReliableMessagingPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ReliableMessagingPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ReliableMessagingPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ReliableMessagingPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ReliableMessagingPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ReliableMessagingPrx ice_collocationOptimized(boolean b)
    {
        return (ReliableMessagingPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ReliableMessagingPrx ice_twoway()
    {
        return (ReliableMessagingPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ReliableMessagingPrx ice_oneway()
    {
        return (ReliableMessagingPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ReliableMessagingPrx ice_batchOneway()
    {
        return (ReliableMessagingPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ReliableMessagingPrx ice_datagram()
    {
        return (ReliableMessagingPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ReliableMessagingPrx ice_batchDatagram()
    {
        return (ReliableMessagingPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ReliableMessagingPrx ice_compress(boolean co)
    {
        return (ReliableMessagingPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ReliableMessagingPrx ice_timeout(int t)
    {
        return (ReliableMessagingPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ReliableMessagingPrx ice_connectionId(String connectionId)
    {
        return (ReliableMessagingPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ReliableMessagingPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ReliableMessagingPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SITMMIO::ReliableMessaging";
    }
}
