//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface ReportConsumerPrx extends com.zeroc.Ice.ObjectPrx
{
    default ReportJob consumeJob()
    {
        return consumeJob(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ReportJob consumeJob(java.util.Map<String, String> context)
    {
        return _iceI_consumeJobAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ReportJob> consumeJobAsync()
    {
        return _iceI_consumeJobAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ReportJob> consumeJobAsync(java.util.Map<String, String> context)
    {
        return _iceI_consumeJobAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ReportJob> _iceI_consumeJobAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ReportJob> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "consumeJob", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     ReportJob ret;
                     ret = ReportJob.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void completeJob(String jobId, String result)
    {
        completeJob(jobId, result, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void completeJob(String jobId, String result, java.util.Map<String, String> context)
    {
        _iceI_completeJobAsync(jobId, result, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> completeJobAsync(String jobId, String result)
    {
        return _iceI_completeJobAsync(jobId, result, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> completeJobAsync(String jobId, String result, java.util.Map<String, String> context)
    {
        return _iceI_completeJobAsync(jobId, result, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param iceP_result -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_completeJobAsync(String iceP_jobId, String iceP_result, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "completeJob", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                     ostr.writeString(iceP_result);
                 }, null);
        return f;
    }

    default void failJob(String jobId, String error)
    {
        failJob(jobId, error, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void failJob(String jobId, String error, java.util.Map<String, String> context)
    {
        _iceI_failJobAsync(jobId, error, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> failJobAsync(String jobId, String error)
    {
        return _iceI_failJobAsync(jobId, error, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> failJobAsync(String jobId, String error, java.util.Map<String, String> context)
    {
        return _iceI_failJobAsync(jobId, error, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param iceP_error -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_failJobAsync(String iceP_jobId, String iceP_error, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "failJob", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                     ostr.writeString(iceP_error);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReportConsumerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ReportConsumerPrx.class, _ReportConsumerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReportConsumerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ReportConsumerPrx.class, _ReportConsumerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReportConsumerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ReportConsumerPrx.class, _ReportConsumerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReportConsumerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ReportConsumerPrx.class, _ReportConsumerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ReportConsumerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ReportConsumerPrx.class, _ReportConsumerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ReportConsumerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ReportConsumerPrx.class, _ReportConsumerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ReportConsumerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ReportConsumerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ReportConsumerPrx ice_adapterId(String newAdapterId)
    {
        return (ReportConsumerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ReportConsumerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ReportConsumerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ReportConsumerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ReportConsumerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ReportConsumerPrx ice_invocationTimeout(int newTimeout)
    {
        return (ReportConsumerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ReportConsumerPrx ice_connectionCached(boolean newCache)
    {
        return (ReportConsumerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ReportConsumerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ReportConsumerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ReportConsumerPrx ice_secure(boolean b)
    {
        return (ReportConsumerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ReportConsumerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ReportConsumerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ReportConsumerPrx ice_preferSecure(boolean b)
    {
        return (ReportConsumerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ReportConsumerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ReportConsumerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ReportConsumerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ReportConsumerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ReportConsumerPrx ice_collocationOptimized(boolean b)
    {
        return (ReportConsumerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ReportConsumerPrx ice_twoway()
    {
        return (ReportConsumerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ReportConsumerPrx ice_oneway()
    {
        return (ReportConsumerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ReportConsumerPrx ice_batchOneway()
    {
        return (ReportConsumerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ReportConsumerPrx ice_datagram()
    {
        return (ReportConsumerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ReportConsumerPrx ice_batchDatagram()
    {
        return (ReportConsumerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ReportConsumerPrx ice_compress(boolean co)
    {
        return (ReportConsumerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ReportConsumerPrx ice_timeout(int t)
    {
        return (ReportConsumerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ReportConsumerPrx ice_connectionId(String connectionId)
    {
        return (ReportConsumerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ReportConsumerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ReportConsumerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SITMMIO::ReportConsumer";
    }
}
