//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class ReportJob implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String jobId;

    public String routeId;

    public String reportType;

    public String status;

    public ReportJob()
    {
        this.jobId = "";
        this.routeId = "";
        this.reportType = "";
        this.status = "";
    }

    public ReportJob(String jobId, String routeId, String reportType, String status)
    {
        this.jobId = jobId;
        this.routeId = routeId;
        this.reportType = reportType;
        this.status = status;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ReportJob r = null;
        if(rhs instanceof ReportJob)
        {
            r = (ReportJob)rhs;
        }

        if(r != null)
        {
            if(this.jobId != r.jobId)
            {
                if(this.jobId == null || r.jobId == null || !this.jobId.equals(r.jobId))
                {
                    return false;
                }
            }
            if(this.routeId != r.routeId)
            {
                if(this.routeId == null || r.routeId == null || !this.routeId.equals(r.routeId))
                {
                    return false;
                }
            }
            if(this.reportType != r.reportType)
            {
                if(this.reportType == null || r.reportType == null || !this.reportType.equals(r.reportType))
                {
                    return false;
                }
            }
            if(this.status != r.status)
            {
                if(this.status == null || r.status == null || !this.status.equals(r.status))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::ReportJob");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, jobId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, reportType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, status);
        return h_;
    }

    public ReportJob clone()
    {
        ReportJob c = null;
        try
        {
            c = (ReportJob)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.jobId);
        ostr.writeString(this.routeId);
        ostr.writeString(this.reportType);
        ostr.writeString(this.status);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.jobId = istr.readString();
        this.routeId = istr.readString();
        this.reportType = istr.readString();
        this.status = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ReportJob v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ReportJob ice_read(com.zeroc.Ice.InputStream istr)
    {
        ReportJob v = new ReportJob();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ReportJob> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ReportJob v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ReportJob> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ReportJob.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ReportJob _nullMarshalValue = new ReportJob();

    /** @hidden */
    public static final long serialVersionUID = -1435455498L;
}
