//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface ReportProducerPrx extends com.zeroc.Ice.ObjectPrx
{
    default String createReportJob(String routeId, String reportType)
    {
        return createReportJob(routeId, reportType, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String createReportJob(String routeId, String reportType, java.util.Map<String, String> context)
    {
        return _iceI_createReportJobAsync(routeId, reportType, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> createReportJobAsync(String routeId, String reportType)
    {
        return _iceI_createReportJobAsync(routeId, reportType, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> createReportJobAsync(String routeId, String reportType, java.util.Map<String, String> context)
    {
        return _iceI_createReportJobAsync(routeId, reportType, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param iceP_reportType -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_createReportJobAsync(String iceP_routeId, String iceP_reportType, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createReportJob", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_routeId);
                     ostr.writeString(iceP_reportType);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default ReportJob getJobStatus(String jobId)
    {
        return getJobStatus(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ReportJob getJobStatus(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getJobStatusAsync(jobId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ReportJob> getJobStatusAsync(String jobId)
    {
        return _iceI_getJobStatusAsync(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ReportJob> getJobStatusAsync(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getJobStatusAsync(jobId, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ReportJob> _iceI_getJobStatusAsync(String iceP_jobId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ReportJob> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getJobStatus", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                 }, istr -> {
                     ReportJob ret;
                     ret = ReportJob.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default ReportJob[] getPendingJobs()
    {
        return getPendingJobs(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ReportJob[] getPendingJobs(java.util.Map<String, String> context)
    {
        return _iceI_getPendingJobsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ReportJob[]> getPendingJobsAsync()
    {
        return _iceI_getPendingJobsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ReportJob[]> getPendingJobsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getPendingJobsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ReportJob[]> _iceI_getPendingJobsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ReportJob[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPendingJobs", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     ReportJob[] ret;
                     ret = ReportJobListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReportProducerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ReportProducerPrx.class, _ReportProducerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReportProducerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ReportProducerPrx.class, _ReportProducerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReportProducerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ReportProducerPrx.class, _ReportProducerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReportProducerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ReportProducerPrx.class, _ReportProducerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ReportProducerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ReportProducerPrx.class, _ReportProducerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ReportProducerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ReportProducerPrx.class, _ReportProducerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ReportProducerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ReportProducerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ReportProducerPrx ice_adapterId(String newAdapterId)
    {
        return (ReportProducerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ReportProducerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ReportProducerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ReportProducerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ReportProducerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ReportProducerPrx ice_invocationTimeout(int newTimeout)
    {
        return (ReportProducerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ReportProducerPrx ice_connectionCached(boolean newCache)
    {
        return (ReportProducerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ReportProducerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ReportProducerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ReportProducerPrx ice_secure(boolean b)
    {
        return (ReportProducerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ReportProducerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ReportProducerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ReportProducerPrx ice_preferSecure(boolean b)
    {
        return (ReportProducerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ReportProducerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ReportProducerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ReportProducerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ReportProducerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ReportProducerPrx ice_collocationOptimized(boolean b)
    {
        return (ReportProducerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ReportProducerPrx ice_twoway()
    {
        return (ReportProducerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ReportProducerPrx ice_oneway()
    {
        return (ReportProducerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ReportProducerPrx ice_batchOneway()
    {
        return (ReportProducerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ReportProducerPrx ice_datagram()
    {
        return (ReportProducerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ReportProducerPrx ice_batchDatagram()
    {
        return (ReportProducerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ReportProducerPrx ice_compress(boolean co)
    {
        return (ReportProducerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ReportProducerPrx ice_timeout(int t)
    {
        return (ReportProducerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ReportProducerPrx ice_connectionId(String connectionId)
    {
        return (ReportProducerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ReportProducerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ReportProducerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SITMMIO::ReportProducer";
    }
}
