//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `RouteService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class RouteSummary implements java.lang.Cloneable,
                                     java.io.Serializable
{
    public String rutaId;

    public int numeroArcos;

    public double distanciaTotal;

    public double tiempoTotal;

    public double velocidadPromedio;

    public RouteSummary()
    {
        this.rutaId = "";
    }

    public RouteSummary(String rutaId, int numeroArcos, double distanciaTotal, double tiempoTotal, double velocidadPromedio)
    {
        this.rutaId = rutaId;
        this.numeroArcos = numeroArcos;
        this.distanciaTotal = distanciaTotal;
        this.tiempoTotal = tiempoTotal;
        this.velocidadPromedio = velocidadPromedio;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RouteSummary r = null;
        if(rhs instanceof RouteSummary)
        {
            r = (RouteSummary)rhs;
        }

        if(r != null)
        {
            if(this.rutaId != r.rutaId)
            {
                if(this.rutaId == null || r.rutaId == null || !this.rutaId.equals(r.rutaId))
                {
                    return false;
                }
            }
            if(this.numeroArcos != r.numeroArcos)
            {
                return false;
            }
            if(this.distanciaTotal != r.distanciaTotal)
            {
                return false;
            }
            if(this.tiempoTotal != r.tiempoTotal)
            {
                return false;
            }
            if(this.velocidadPromedio != r.velocidadPromedio)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::RouteSummary");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, rutaId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, numeroArcos);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, distanciaTotal);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tiempoTotal);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, velocidadPromedio);
        return h_;
    }

    public RouteSummary clone()
    {
        RouteSummary c = null;
        try
        {
            c = (RouteSummary)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.rutaId);
        ostr.writeInt(this.numeroArcos);
        ostr.writeDouble(this.distanciaTotal);
        ostr.writeDouble(this.tiempoTotal);
        ostr.writeDouble(this.velocidadPromedio);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.rutaId = istr.readString();
        this.numeroArcos = istr.readInt();
        this.distanciaTotal = istr.readDouble();
        this.tiempoTotal = istr.readDouble();
        this.velocidadPromedio = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, RouteSummary v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public RouteSummary ice_read(com.zeroc.Ice.InputStream istr)
    {
        RouteSummary v = new RouteSummary();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RouteSummary> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, RouteSummary v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<RouteSummary> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(RouteSummary.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final RouteSummary _nullMarshalValue = new RouteSummary();

    /** @hidden */
    public static final long serialVersionUID = 6006900L;
}
