//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `RouteService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class RouteInfo implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String routeId;

    public String nombre;

    public String descripcion;

    public int numeroParadas;

    public double distanciaTotal;

    public double tiempoTotal;

    public double velocidadPromedio;

    public RouteInfo()
    {
        this.routeId = "";
        this.nombre = "";
        this.descripcion = "";
    }

    public RouteInfo(String routeId, String nombre, String descripcion, int numeroParadas, double distanciaTotal, double tiempoTotal, double velocidadPromedio)
    {
        this.routeId = routeId;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.numeroParadas = numeroParadas;
        this.distanciaTotal = distanciaTotal;
        this.tiempoTotal = tiempoTotal;
        this.velocidadPromedio = velocidadPromedio;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RouteInfo r = null;
        if(rhs instanceof RouteInfo)
        {
            r = (RouteInfo)rhs;
        }

        if(r != null)
        {
            if(this.routeId != r.routeId)
            {
                if(this.routeId == null || r.routeId == null || !this.routeId.equals(r.routeId))
                {
                    return false;
                }
            }
            if(this.nombre != r.nombre)
            {
                if(this.nombre == null || r.nombre == null || !this.nombre.equals(r.nombre))
                {
                    return false;
                }
            }
            if(this.descripcion != r.descripcion)
            {
                if(this.descripcion == null || r.descripcion == null || !this.descripcion.equals(r.descripcion))
                {
                    return false;
                }
            }
            if(this.numeroParadas != r.numeroParadas)
            {
                return false;
            }
            if(this.distanciaTotal != r.distanciaTotal)
            {
                return false;
            }
            if(this.tiempoTotal != r.tiempoTotal)
            {
                return false;
            }
            if(this.velocidadPromedio != r.velocidadPromedio)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::RouteInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nombre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, descripcion);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, numeroParadas);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, distanciaTotal);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tiempoTotal);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, velocidadPromedio);
        return h_;
    }

    public RouteInfo clone()
    {
        RouteInfo c = null;
        try
        {
            c = (RouteInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.routeId);
        ostr.writeString(this.nombre);
        ostr.writeString(this.descripcion);
        ostr.writeInt(this.numeroParadas);
        ostr.writeDouble(this.distanciaTotal);
        ostr.writeDouble(this.tiempoTotal);
        ostr.writeDouble(this.velocidadPromedio);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.routeId = istr.readString();
        this.nombre = istr.readString();
        this.descripcion = istr.readString();
        this.numeroParadas = istr.readInt();
        this.distanciaTotal = istr.readDouble();
        this.tiempoTotal = istr.readDouble();
        this.velocidadPromedio = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, RouteInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public RouteInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        RouteInfo v = new RouteInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RouteInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, RouteInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<RouteInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(RouteInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final RouteInfo _nullMarshalValue = new RouteInfo();

    /** @hidden */
    public static final long serialVersionUID = 656336141L;
}
