//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `RouteService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class RouteNotFoundException extends com.zeroc.Ice.UserException
{
    public RouteNotFoundException()
    {
        this.routeId = "";
    }

    public RouteNotFoundException(Throwable cause)
    {
        super(cause);
        this.routeId = "";
    }

    public RouteNotFoundException(String routeId)
    {
        this.routeId = routeId;
    }

    public RouteNotFoundException(String routeId, Throwable cause)
    {
        super(cause);
        this.routeId = routeId;
    }

    public String ice_id()
    {
        return "::SITMMIO::RouteNotFoundException";
    }

    public String routeId;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SITMMIO::RouteNotFoundException", -1, true);
        ostr_.writeString(routeId);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        routeId = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 1271879261L;
}
