//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `RouteService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface RouteService extends com.zeroc.Ice.Object
{
    RouteInfo[] obtenerTodasLasRutas(com.zeroc.Ice.Current current);

    RouteInfo obtenerInformacionRuta(String routeId, com.zeroc.Ice.Current current)
        throws RouteNotFoundException;

    ArcDetail[] obtenerArcosDeRuta(String routeId, com.zeroc.Ice.Current current)
        throws RouteNotFoundException;

    RouteSummary obtenerResumenRuta(String routeId, com.zeroc.Ice.Current current)
        throws RouteNotFoundException;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::SITMMIO::RouteService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::SITMMIO::RouteService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerTodasLasRutas(RouteService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        RouteInfo[] ret = obj.obtenerTodasLasRutas(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        RouteInfoListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerInformacionRuta(RouteService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_routeId;
        iceP_routeId = istr.readString();
        inS.endReadParams();
        RouteInfo ret = obj.obtenerInformacionRuta(iceP_routeId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        RouteInfo.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerArcosDeRuta(RouteService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_routeId;
        iceP_routeId = istr.readString();
        inS.endReadParams();
        ArcDetail[] ret = obj.obtenerArcosDeRuta(iceP_routeId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcDetailListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerResumenRuta(RouteService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_routeId;
        iceP_routeId = istr.readString();
        inS.endReadParams();
        RouteSummary ret = obj.obtenerResumenRuta(iceP_routeId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        RouteSummary.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "obtenerArcosDeRuta",
        "obtenerInformacionRuta",
        "obtenerResumenRuta",
        "obtenerTodasLasRutas"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 1:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 4:
            {
                return _iceD_obtenerArcosDeRuta(this, in, current);
            }
            case 5:
            {
                return _iceD_obtenerInformacionRuta(this, in, current);
            }
            case 6:
            {
                return _iceD_obtenerResumenRuta(this, in, current);
            }
            case 7:
            {
                return _iceD_obtenerTodasLasRutas(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
