//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `RouteService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public interface RouteServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default RouteInfo[] obtenerTodasLasRutas()
    {
        return obtenerTodasLasRutas(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default RouteInfo[] obtenerTodasLasRutas(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTodasLasRutasAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<RouteInfo[]> obtenerTodasLasRutasAsync()
    {
        return _iceI_obtenerTodasLasRutasAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<RouteInfo[]> obtenerTodasLasRutasAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTodasLasRutasAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<RouteInfo[]> _iceI_obtenerTodasLasRutasAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<RouteInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerTodasLasRutas", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     RouteInfo[] ret;
                     ret = RouteInfoListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default RouteInfo obtenerInformacionRuta(String routeId)
        throws RouteNotFoundException
    {
        return obtenerInformacionRuta(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default RouteInfo obtenerInformacionRuta(String routeId, java.util.Map<String, String> context)
        throws RouteNotFoundException
    {
        try
        {
            return _iceI_obtenerInformacionRutaAsync(routeId, context, true).waitForResponseOrUserEx();
        }
        catch(RouteNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<RouteInfo> obtenerInformacionRutaAsync(String routeId)
    {
        return _iceI_obtenerInformacionRutaAsync(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<RouteInfo> obtenerInformacionRutaAsync(String routeId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerInformacionRutaAsync(routeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<RouteInfo> _iceI_obtenerInformacionRutaAsync(String iceP_routeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<RouteInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerInformacionRuta", null, sync, _iceE_obtenerInformacionRuta);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_routeId);
                 }, istr -> {
                     RouteInfo ret;
                     ret = RouteInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_obtenerInformacionRuta =
    {
        RouteNotFoundException.class
    };

    default ArcDetail[] obtenerArcosDeRuta(String routeId)
        throws RouteNotFoundException
    {
        return obtenerArcosDeRuta(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcDetail[] obtenerArcosDeRuta(String routeId, java.util.Map<String, String> context)
        throws RouteNotFoundException
    {
        try
        {
            return _iceI_obtenerArcosDeRutaAsync(routeId, context, true).waitForResponseOrUserEx();
        }
        catch(RouteNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<ArcDetail[]> obtenerArcosDeRutaAsync(String routeId)
    {
        return _iceI_obtenerArcosDeRutaAsync(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcDetail[]> obtenerArcosDeRutaAsync(String routeId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerArcosDeRutaAsync(routeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcDetail[]> _iceI_obtenerArcosDeRutaAsync(String iceP_routeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcDetail[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerArcosDeRuta", null, sync, _iceE_obtenerArcosDeRuta);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_routeId);
                 }, istr -> {
                     ArcDetail[] ret;
                     ret = ArcDetailListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_obtenerArcosDeRuta =
    {
        RouteNotFoundException.class
    };

    default RouteSummary obtenerResumenRuta(String routeId)
        throws RouteNotFoundException
    {
        return obtenerResumenRuta(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default RouteSummary obtenerResumenRuta(String routeId, java.util.Map<String, String> context)
        throws RouteNotFoundException
    {
        try
        {
            return _iceI_obtenerResumenRutaAsync(routeId, context, true).waitForResponseOrUserEx();
        }
        catch(RouteNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<RouteSummary> obtenerResumenRutaAsync(String routeId)
    {
        return _iceI_obtenerResumenRutaAsync(routeId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<RouteSummary> obtenerResumenRutaAsync(String routeId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerResumenRutaAsync(routeId, context, false);
    }

    /**
     * @hidden
     * @param iceP_routeId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<RouteSummary> _iceI_obtenerResumenRutaAsync(String iceP_routeId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<RouteSummary> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerResumenRuta", null, sync, _iceE_obtenerResumenRuta);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_routeId);
                 }, istr -> {
                     RouteSummary ret;
                     ret = RouteSummary.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_obtenerResumenRuta =
    {
        RouteNotFoundException.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RouteServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RouteServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RouteServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RouteServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static RouteServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static RouteServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, RouteServicePrx.class, _RouteServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default RouteServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (RouteServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default RouteServicePrx ice_adapterId(String newAdapterId)
    {
        return (RouteServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default RouteServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (RouteServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default RouteServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (RouteServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default RouteServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (RouteServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default RouteServicePrx ice_connectionCached(boolean newCache)
    {
        return (RouteServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default RouteServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (RouteServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default RouteServicePrx ice_secure(boolean b)
    {
        return (RouteServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default RouteServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (RouteServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default RouteServicePrx ice_preferSecure(boolean b)
    {
        return (RouteServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default RouteServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (RouteServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default RouteServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (RouteServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default RouteServicePrx ice_collocationOptimized(boolean b)
    {
        return (RouteServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default RouteServicePrx ice_twoway()
    {
        return (RouteServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default RouteServicePrx ice_oneway()
    {
        return (RouteServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default RouteServicePrx ice_batchOneway()
    {
        return (RouteServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default RouteServicePrx ice_datagram()
    {
        return (RouteServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default RouteServicePrx ice_batchDatagram()
    {
        return (RouteServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default RouteServicePrx ice_compress(boolean co)
    {
        return (RouteServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default RouteServicePrx ice_timeout(int t)
    {
        return (RouteServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default RouteServicePrx ice_connectionId(String connectionId)
    {
        return (RouteServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default RouteServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (RouteServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SITMMIO::RouteService";
    }
}
