//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class ServiceInfo implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public String serviceName;

    public String endpoint;

    public String serviceType;

    public int load;

    public ServiceInfo()
    {
        this.serviceName = "";
        this.endpoint = "";
        this.serviceType = "";
    }

    public ServiceInfo(String serviceName, String endpoint, String serviceType, int load)
    {
        this.serviceName = serviceName;
        this.endpoint = endpoint;
        this.serviceType = serviceType;
        this.load = load;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ServiceInfo r = null;
        if(rhs instanceof ServiceInfo)
        {
            r = (ServiceInfo)rhs;
        }

        if(r != null)
        {
            if(this.serviceName != r.serviceName)
            {
                if(this.serviceName == null || r.serviceName == null || !this.serviceName.equals(r.serviceName))
                {
                    return false;
                }
            }
            if(this.endpoint != r.endpoint)
            {
                if(this.endpoint == null || r.endpoint == null || !this.endpoint.equals(r.endpoint))
                {
                    return false;
                }
            }
            if(this.serviceType != r.serviceType)
            {
                if(this.serviceType == null || r.serviceType == null || !this.serviceType.equals(r.serviceType))
                {
                    return false;
                }
            }
            if(this.load != r.load)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::ServiceInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, serviceName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, endpoint);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, serviceType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, load);
        return h_;
    }

    public ServiceInfo clone()
    {
        ServiceInfo c = null;
        try
        {
            c = (ServiceInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.serviceName);
        ostr.writeString(this.endpoint);
        ostr.writeString(this.serviceType);
        ostr.writeInt(this.load);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.serviceName = istr.readString();
        this.endpoint = istr.readString();
        this.serviceType = istr.readString();
        this.load = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ServiceInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ServiceInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        ServiceInfo v = new ServiceInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ServiceInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ServiceInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ServiceInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ServiceInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ServiceInfo _nullMarshalValue = new ServiceInfo();

    /** @hidden */
    public static final long serialVersionUID = 193683498L;
}
