//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

/**
 * Helper class for marshaling/unmarshaling ServiceInfoList.
 **/
public final class ServiceInfoListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, ServiceInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ServiceInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ServiceInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final ServiceInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(7);
        v = new ServiceInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = ServiceInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ServiceInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ServiceInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ServiceInfoListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<ServiceInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            ServiceInfo[] v;
            v = ServiceInfoListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
