//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `AnalysisService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class VelocityAnalysis implements java.lang.Cloneable,
                                         java.io.Serializable
{
    public String routeId;

    public double velocidadPromedio;

    public double velocidadMaxima;

    public double velocidadMinima;

    public int numeroArcos;

    public VelocityAnalysis()
    {
        this.routeId = "";
    }

    public VelocityAnalysis(String routeId, double velocidadPromedio, double velocidadMaxima, double velocidadMinima, int numeroArcos)
    {
        this.routeId = routeId;
        this.velocidadPromedio = velocidadPromedio;
        this.velocidadMaxima = velocidadMaxima;
        this.velocidadMinima = velocidadMinima;
        this.numeroArcos = numeroArcos;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        VelocityAnalysis r = null;
        if(rhs instanceof VelocityAnalysis)
        {
            r = (VelocityAnalysis)rhs;
        }

        if(r != null)
        {
            if(this.routeId != r.routeId)
            {
                if(this.routeId == null || r.routeId == null || !this.routeId.equals(r.routeId))
                {
                    return false;
                }
            }
            if(this.velocidadPromedio != r.velocidadPromedio)
            {
                return false;
            }
            if(this.velocidadMaxima != r.velocidadMaxima)
            {
                return false;
            }
            if(this.velocidadMinima != r.velocidadMinima)
            {
                return false;
            }
            if(this.numeroArcos != r.numeroArcos)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::VelocityAnalysis");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, velocidadPromedio);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, velocidadMaxima);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, velocidadMinima);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, numeroArcos);
        return h_;
    }

    public VelocityAnalysis clone()
    {
        VelocityAnalysis c = null;
        try
        {
            c = (VelocityAnalysis)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.routeId);
        ostr.writeDouble(this.velocidadPromedio);
        ostr.writeDouble(this.velocidadMaxima);
        ostr.writeDouble(this.velocidadMinima);
        ostr.writeInt(this.numeroArcos);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.routeId = istr.readString();
        this.velocidadPromedio = istr.readDouble();
        this.velocidadMaxima = istr.readDouble();
        this.velocidadMinima = istr.readDouble();
        this.numeroArcos = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, VelocityAnalysis v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public VelocityAnalysis ice_read(com.zeroc.Ice.InputStream istr)
    {
        VelocityAnalysis v = new VelocityAnalysis();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<VelocityAnalysis> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, VelocityAnalysis v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<VelocityAnalysis> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(VelocityAnalysis.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final VelocityAnalysis _nullMarshalValue = new VelocityAnalysis();

    /** @hidden */
    public static final long serialVersionUID = 206395861L;
}
