//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class WorkTask implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public String taskId;

    public String routeId;

    public String taskType;

    public int priority;

    public WorkTask()
    {
        this.taskId = "";
        this.routeId = "";
        this.taskType = "";
    }

    public WorkTask(String taskId, String routeId, String taskType, int priority)
    {
        this.taskId = taskId;
        this.routeId = routeId;
        this.taskType = taskType;
        this.priority = priority;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        WorkTask r = null;
        if(rhs instanceof WorkTask)
        {
            r = (WorkTask)rhs;
        }

        if(r != null)
        {
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }
            if(this.routeId != r.routeId)
            {
                if(this.routeId == null || r.routeId == null || !this.routeId.equals(r.routeId))
                {
                    return false;
                }
            }
            if(this.taskType != r.taskType)
            {
                if(this.taskType == null || r.taskType == null || !this.taskType.equals(r.taskType))
                {
                    return false;
                }
            }
            if(this.priority != r.priority)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::WorkTask");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routeId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, priority);
        return h_;
    }

    public WorkTask clone()
    {
        WorkTask c = null;
        try
        {
            c = (WorkTask)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.taskId);
        ostr.writeString(this.routeId);
        ostr.writeString(this.taskType);
        ostr.writeInt(this.priority);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.taskId = istr.readString();
        this.routeId = istr.readString();
        this.taskType = istr.readString();
        this.priority = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, WorkTask v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public WorkTask ice_read(com.zeroc.Ice.InputStream istr)
    {
        WorkTask v = new WorkTask();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<WorkTask> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, WorkTask v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<WorkTask> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(WorkTask.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final WorkTask _nullMarshalValue = new WorkTask();

    /** @hidden */
    public static final long serialVersionUID = -388820516L;
}
