//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Patterns.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITMMIO;

public class WorkResult implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public String taskId;

    public boolean success;

    public String resultData;

    public double processingTime;

    public WorkResult()
    {
        this.taskId = "";
        this.resultData = "";
    }

    public WorkResult(String taskId, boolean success, String resultData, double processingTime)
    {
        this.taskId = taskId;
        this.success = success;
        this.resultData = resultData;
        this.processingTime = processingTime;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        WorkResult r = null;
        if(rhs instanceof WorkResult)
        {
            r = (WorkResult)rhs;
        }

        if(r != null)
        {
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }
            if(this.success != r.success)
            {
                return false;
            }
            if(this.resultData != r.resultData)
            {
                if(this.resultData == null || r.resultData == null || !this.resultData.equals(r.resultData))
                {
                    return false;
                }
            }
            if(this.processingTime != r.processingTime)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SITMMIO::WorkResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, success);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, resultData);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, processingTime);
        return h_;
    }

    public WorkResult clone()
    {
        WorkResult c = null;
        try
        {
            c = (WorkResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.taskId);
        ostr.writeBool(this.success);
        ostr.writeString(this.resultData);
        ostr.writeDouble(this.processingTime);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.taskId = istr.readString();
        this.success = istr.readBool();
        this.resultData = istr.readString();
        this.processingTime = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, WorkResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public WorkResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        WorkResult v = new WorkResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<WorkResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, WorkResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<WorkResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(WorkResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final WorkResult _nullMarshalValue = new WorkResult();

    /** @hidden */
    public static final long serialVersionUID = -4700753L;
}
